# Generated by @xeokit/demos ./build-convert-models.js
echo [convert-models.sh] Converting 27 files...

# --------------------------------------
# SmallHouse
# --------------------------------------
echo [convert-models.sh] Converting SmallHouse

# dotbim2xgf
node ../sdk/dist/dotbim2xgf/dotbim2xgf.js -i ./models/SmallHouse/dotbim/model.bim -s ./models/SmallHouse/dotbim2xgf/model.xgf -d ./models/SmallHouse/dotbim2xgf/model.json -l >> ./models/SmallHouse/dotbim2xgf/log.txt
echo [convert-models.sh] Converted SmallHouse via dotbim2xgf
echo [convert-models.sh] 1 out of 27 conversions done

# --------------------------------------
# HousePlan
# --------------------------------------
echo [convert-models.sh] Converting HousePlan

# gltf2xgf
node ../sdk/dist/gltf2xgf/gltf2xgf.js -i ./models/HousePlan/gltf/model.glb -s ./models/HousePlan/gltf2xgf/model.xgf -d ./models/HousePlan/gltf2xgf/model.json -l >> ./models/HousePlan/gltf2xgf/log.txt
echo [convert-models.sh] Converted HousePlan via gltf2xgf
echo [convert-models.sh] 2 out of 27 conversions done

# --------------------------------------
# TeapotXeokitLogo
# --------------------------------------
echo [convert-models.sh] Converting TeapotXeokitLogo

# dotbim2xgf
node ../sdk/dist/dotbim2xgf/dotbim2xgf.js -i ./models/TeapotXeokitLogo/dotbim/model.bim -s ./models/TeapotXeokitLogo/dotbim2xgf/model.xgf -d ./models/TeapotXeokitLogo/dotbim2xgf/model.json -l >> ./models/TeapotXeokitLogo/dotbim2xgf/log.txt
echo [convert-models.sh] Converted TeapotXeokitLogo via dotbim2xgf
echo [convert-models.sh] 3 out of 27 conversions done

# --------------------------------------
# BlenderHouse
# --------------------------------------
echo [convert-models.sh] Converting BlenderHouse

# dotbim2xgf
node ../sdk/dist/dotbim2xgf/dotbim2xgf.js -i ./models/BlenderHouse/dotbim/model.bim -s ./models/BlenderHouse/dotbim2xgf/model.xgf -d ./models/BlenderHouse/dotbim2xgf/model.json -l >> ./models/BlenderHouse/dotbim2xgf/log.txt
echo [convert-models.sh] Converted BlenderHouse via dotbim2xgf
echo [convert-models.sh] 4 out of 27 conversions done

# --------------------------------------
# MAP
# --------------------------------------
echo [convert-models.sh] Converting MAP

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/MAP/ifc/model.ifc -o ./models/MAP/ifc2gltf/model.glb -m ./models/MAP/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/MAP/ifc2gltf/log.txt
echo [convert-models.sh] Converted MAP via ifc2gltf
echo [convert-models.sh] 5 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/MAP/ifc2gltf/model.manifest.json -o ./models/MAP/ifc2gltf2xgf/model.manifest.json -l >> ./models/MAP/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted MAP via ifc2gltf2xgf
echo [convert-models.sh] 6 out of 27 conversions done

# gltf2xgf
node ../sdk/dist/gltf2xgf/gltf2xgf.js -i ./models/MAP/gltf/model.glb -s ./models/MAP/gltf2xgf/model.xgf -d ./models/MAP/gltf2xgf/model.json -l >> ./models/MAP/gltf2xgf/log.txt
echo [convert-models.sh] Converted MAP via gltf2xgf
echo [convert-models.sh] 7 out of 27 conversions done

# webifc2xgf
node ../sdk/dist/webifc2xgf/webifc2xgf.js -i ./models/MAP/ifc/model.ifc -s ./models/MAP/webifc2xgf/model.xgf -d ./models/MAP/webifc2xgf/model.json -l >> ./models/MAP/webifc2xgf/log.txt
echo [convert-models.sh] Converted MAP via webifc2xgf
echo [convert-models.sh] 8 out of 27 conversions done

# --------------------------------------
# Duplex
# --------------------------------------
echo [convert-models.sh] Converting Duplex

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/Duplex/ifc/model.ifc -o ./models/Duplex/ifc2gltf/model.glb -m ./models/Duplex/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/Duplex/ifc2gltf/log.txt
echo [convert-models.sh] Converted Duplex via ifc2gltf
echo [convert-models.sh] 9 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/Duplex/ifc2gltf/model.manifest.json -o ./models/Duplex/ifc2gltf2xgf/model.manifest.json -l >> ./models/Duplex/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted Duplex via ifc2gltf2xgf
echo [convert-models.sh] 10 out of 27 conversions done

# gltf2xgf
node ../sdk/dist/gltf2xgf/gltf2xgf.js -i ./models/Duplex/gltf/model.glb -s ./models/Duplex/gltf2xgf/model.xgf -d ./models/Duplex/gltf2xgf/model.json -l >> ./models/Duplex/gltf2xgf/log.txt
echo [convert-models.sh] Converted Duplex via gltf2xgf
echo [convert-models.sh] 11 out of 27 conversions done

# webifc2xgf
node ../sdk/dist/webifc2xgf/webifc2xgf.js -i ./models/Duplex/ifc/model.ifc -s ./models/Duplex/webifc2xgf/model.xgf -d ./models/Duplex/webifc2xgf/model.json -l >> ./models/Duplex/webifc2xgf/log.txt
echo [convert-models.sh] Converted Duplex via webifc2xgf
echo [convert-models.sh] 12 out of 27 conversions done

# --------------------------------------
# IfcOpenHouse4
# --------------------------------------
echo [convert-models.sh] Converting IfcOpenHouse4

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/IfcOpenHouse4/ifc/model.ifc -o ./models/IfcOpenHouse4/ifc2gltf/model.glb -m ./models/IfcOpenHouse4/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/IfcOpenHouse4/ifc2gltf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse4 via ifc2gltf
echo [convert-models.sh] 13 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/IfcOpenHouse4/ifc2gltf/model.manifest.json -o ./models/IfcOpenHouse4/ifc2gltf2xgf/model.manifest.json -l >> ./models/IfcOpenHouse4/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse4 via ifc2gltf2xgf
echo [convert-models.sh] 14 out of 27 conversions done

# webifc2xgf
node ../sdk/dist/webifc2xgf/webifc2xgf.js -i ./models/IfcOpenHouse4/ifc/model.ifc -s ./models/IfcOpenHouse4/webifc2xgf/model.xgf -d ./models/IfcOpenHouse4/webifc2xgf/model.json -l >> ./models/IfcOpenHouse4/webifc2xgf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse4 via webifc2xgf
echo [convert-models.sh] 15 out of 27 conversions done

# dotbim2xgf
node ../sdk/dist/dotbim2xgf/dotbim2xgf.js -i ./models/IfcOpenHouse4/dotbim/model.bim -s ./models/IfcOpenHouse4/dotbim2xgf/model.xgf -d ./models/IfcOpenHouse4/dotbim2xgf/model.json -l >> ./models/IfcOpenHouse4/dotbim2xgf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse4 via dotbim2xgf
echo [convert-models.sh] 16 out of 27 conversions done

# --------------------------------------
# IfcOpenHouse2x3
# --------------------------------------
echo [convert-models.sh] Converting IfcOpenHouse2x3

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/IfcOpenHouse2x3/ifc/model.ifc -o ./models/IfcOpenHouse2x3/ifc2gltf/model.glb -m ./models/IfcOpenHouse2x3/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/IfcOpenHouse2x3/ifc2gltf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse2x3 via ifc2gltf
echo [convert-models.sh] 17 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/IfcOpenHouse2x3/ifc2gltf/model.manifest.json -o ./models/IfcOpenHouse2x3/ifc2gltf2xgf/model.manifest.json -l >> ./models/IfcOpenHouse2x3/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse2x3 via ifc2gltf2xgf
echo [convert-models.sh] 18 out of 27 conversions done

# webifc2xgf
node ../sdk/dist/webifc2xgf/webifc2xgf.js -i ./models/IfcOpenHouse2x3/ifc/model.ifc -s ./models/IfcOpenHouse2x3/webifc2xgf/model.xgf -d ./models/IfcOpenHouse2x3/webifc2xgf/model.json -l >> ./models/IfcOpenHouse2x3/webifc2xgf/log.txt
echo [convert-models.sh] Converted IfcOpenHouse2x3 via webifc2xgf
echo [convert-models.sh] 19 out of 27 conversions done

# --------------------------------------
# Nalls-Pumpkin-Hill
# --------------------------------------
echo [convert-models.sh] Converting Nalls-Pumpkin-Hill

# las2xgf
node ../sdk/dist/las2xgf/las2xgf.js -i ./models/Nalls-Pumpkin-Hill/laz/model.* -s ./models/Nalls-Pumpkin-Hill/las2xgf/model.xgf -d ./models/Nalls-Pumpkin-Hill/las2xgf/model.json -l >> ./models/Nalls-Pumpkin-Hill/las2xgf/log.txt
echo [convert-models.sh] Converted Nalls-Pumpkin-Hill via las2xgf
echo [convert-models.sh] 20 out of 27 conversions done

# --------------------------------------
# KarhumakiBridge
# --------------------------------------
echo [convert-models.sh] Converting KarhumakiBridge

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/KarhumakiBridge/ifc/model.ifc -o ./models/KarhumakiBridge/ifc2gltf/model.glb -m ./models/KarhumakiBridge/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/KarhumakiBridge/ifc2gltf/log.txt
echo [convert-models.sh] Converted KarhumakiBridge via ifc2gltf
echo [convert-models.sh] 21 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/KarhumakiBridge/ifc2gltf/model.manifest.json -o ./models/KarhumakiBridge/ifc2gltf2xgf/model.manifest.json -l >> ./models/KarhumakiBridge/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted KarhumakiBridge via ifc2gltf2xgf
echo [convert-models.sh] 22 out of 27 conversions done

# --------------------------------------
# Schependomlaan
# --------------------------------------
echo [convert-models.sh] Converting Schependomlaan

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/Schependomlaan/ifc/model.ifc -o ./models/Schependomlaan/ifc2gltf/model.glb -m ./models/Schependomlaan/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/Schependomlaan/ifc2gltf/log.txt
echo [convert-models.sh] Converted Schependomlaan via ifc2gltf
echo [convert-models.sh] 23 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/Schependomlaan/ifc2gltf/model.manifest.json -o ./models/Schependomlaan/ifc2gltf2xgf/model.manifest.json -l >> ./models/Schependomlaan/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted Schependomlaan via ifc2gltf2xgf
echo [convert-models.sh] 24 out of 27 conversions done

# --------------------------------------
# RAC
# --------------------------------------
echo [convert-models.sh] Converting RAC

# ifc2gltf
/home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter_static -c /home/lindsay/xeolabs/xeokit/ifc2gltf/4_34_4_beta/linux//ifc2gltfcxconverter.json -i ./models/RAC/ifc/model.ifc -o ./models/RAC/ifc2gltf/model.glb -m ./models/RAC/ifc2gltf/model.json -s 20 -t 1000 -e 3 >> ./models/RAC/ifc2gltf/log.txt
echo [convert-models.sh] Converted RAC via ifc2gltf
echo [convert-models.sh] 25 out of 27 conversions done

# ifc2gltf2xgf
node ../sdk/dist/ifc2gltf2xgf/ifc2gltf2xgf.js -i ./models/RAC/ifc2gltf/model.manifest.json -o ./models/RAC/ifc2gltf2xgf/model.manifest.json -l >> ./models/RAC/ifc2gltf2xgf/log.txt
echo [convert-models.sh] Converted RAC via ifc2gltf2xgf
echo [convert-models.sh] 26 out of 27 conversions done

# webifc2xgf
node ../sdk/dist/webifc2xgf/webifc2xgf.js -i ./models/RAC/ifc/model.ifc -s ./models/RAC/webifc2xgf/model.xgf -d ./models/RAC/webifc2xgf/model.json -l >> ./models/RAC/webifc2xgf/log.txt
echo [convert-models.sh] Converted RAC via webifc2xgf
echo [convert-models.sh] 27 out of 27 conversions done