/**
 * Provides info on the [XGF](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xgf) generated by {@link @xeokit/xgf!XKFWriter | XKFWriter}.
 *
 * See {@link "@xeokit/xgf" | @xeokit/xgf} for usage.
 */
export const XGF_INFO = {
    /**
     * The [XGF](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xgf) version generated by {@link @xeokit/xgf!XKFWriter | XKFWriter}.
     *
     * @property xgfVersion
     * @type {number}
     */
    xgfVersion: 1
};
//# sourceMappingURL=XGF_INFO.js.map
