import {type ModelConverterStatsReportInput} from "./ModelConverterStatsReportInput";
import {type ModelConverterStatsReportOutput} from "./ModelConverterStatsReportOutput";
import {type SceneModelStats} from "../../../scene";
import {type DataModelStats} from "../../../data";

/**
 * Represents a detailed report generated by a model conversion process.
 *
 * This includes metadata about the command, pipeline, and timestamps, as well as
 * statistics about inputs, outputs, scene models, and data models involved in the conversion.
 */
export interface ModelConverterStatsReport {

  /**
   * A human-readable description of the conversion task.
   */
  description: string;

  /**
   * The exact command used to initiate the conversion.
   */
  command: string;

  /**
   * The timestamp or duration of when the conversion occurred.
   */
  time: string;

  /**
   * The name or identifier of the processing pipeline used.
   */
  pipeline: string;

  /**
   * A map of input identifiers to their corresponding input statistics.
   */
  inputs: {
    [key: string]: ModelConverterStatsReportInput;
  };

  /**
   * A map of {@link scene!SceneModel | SceneModel} identifiers to their corresponding statistics.
   */
  sceneModels: {
    [key: string]: SceneModelStats;
  };

  /**
   * A map of {@link data!DataModel | DataModel} identifiers to their corresponding statistics.
   */
  dataModels: {
    [key: string]: DataModelStats;
  };

  /**
   * A map of output identifiers to their corresponding output statistics.
   */
  outputs: {
    [key: string]: ModelConverterStatsReportOutput;
  };

  /**
   * Any errors that occurred during the conversion process.
   */
  errors: string[];
}
