import {createUUID} from "../../../../utils";
import type {ModelEncodeParams} from "../../../ModelEncodeParams";
import * as WebIFC from "web-ifc";
import {decompressPoint3WithAABB3} from "../../../../math/compression";
import {Data} from "../../../../data";
import {createDefaultIFCDataModel} from "../../createDefaultIFCDataModel";

// Reusable scratch buffers for position decompression — avoids per-vertex allocation
const _compressedPos = new Float32Array(3);
const _decompressedPos = new Float64Array(3);

/** @private */
export function encode(ifcAPI: WebIFC.IfcAPI, params: ModelEncodeParams, options?: any): Promise<any> {
  return new Promise<any>(function (resolve, reject) {

    const {sceneModel} = params;

    let dataModel;

    if (!params.dataModel || params.dataModel.objectsByType?.["IfcProject"] === undefined) {
      const data = new Data(); // GCd after encoding
      const dataModelRes = data.createModel({
        id: sceneModel.id
      });
      if (dataModelRes.ok !== true) {
        reject("[IFC4 encode] Failed to create DataModel: " + dataModelRes.error);
        return;
      }
      dataModel = dataModelRes.value;
      createDefaultIFCDataModel(sceneModel, dataModel);
    } else {
      dataModel = params.dataModel;
    }

    const modelId = ifcAPI.CreateModel({
      schema: WebIFC.Schemas.IFC4,
      name: dataModel?.name || "Model",
      description: ["Generated by xeokit SDK"],
      authors: [dataModel?.author || "xeokit"],
      organizations: []
    });

    // -------------------------------------------------------------------------
    // Boilerplate: organisation, application, owner history
    // -------------------------------------------------------------------------

    const org = new WebIFC.IFC4.IfcOrganization(
      null,
      new WebIFC.IFC4.IfcLabel(dataModel?.creatingApplication || "xeokit"),
      null, null, null
    );
    ifcAPI.WriteLine(modelId, org);

    const app = new WebIFC.IFC4.IfcApplication(
      org,
      new WebIFC.IFC4.IfcLabel("1.0.0"),
      new WebIFC.IFC4.IfcLabel("xeokit SDK"),
      new WebIFC.IFC4.IfcIdentifier("xeokit-sdk")
    );
    ifcAPI.WriteLine(modelId, app);

    const person = new WebIFC.IFC4.IfcPerson(
      null, new WebIFC.IFC4.IfcLabel(""), null, null, null, null, null, null
    );
    ifcAPI.WriteLine(modelId, person);

    const personAndOrg = new WebIFC.IFC4.IfcPersonAndOrganization(person, org, null);
    ifcAPI.WriteLine(modelId, personAndOrg);

    const ownerHistory = new WebIFC.IFC4.IfcOwnerHistory(
      personAndOrg, app,
      null, null, null, null, null,
      new WebIFC.IFC4.IfcTimeStamp(Math.floor(Date.now() / 1000))
    );
    ifcAPI.WriteLine(modelId, ownerHistory);

    // -------------------------------------------------------------------------
    // Units: metre (length), square metre (area), cubic metre (volume)
    // -------------------------------------------------------------------------

    // IfcSIUnit(UnitType, Prefix, Name) — Dimensions is a derived attribute, not a constructor param
    const lenUnit  = new WebIFC.IFC4.IfcSIUnit(null, null, (<any>WebIFC.IFC4.IfcSIUnitName).METRE);
    const areaUnit = new WebIFC.IFC4.IfcSIUnit(null, null, (<any>WebIFC.IFC4.IfcSIUnitName).SQUARE_METRE);
    const volUnit  = new WebIFC.IFC4.IfcSIUnit(null, null, (<any>WebIFC.IFC4.IfcSIUnitName).CUBIC_METRE);
    const unitAssign = new WebIFC.IFC4.IfcUnitAssignment([lenUnit, areaUnit, volUnit]);
    ifcAPI.WriteLine(modelId, unitAssign);

    // -------------------------------------------------------------------------
    // Geometric representation context
    // -------------------------------------------------------------------------

    const worldOrigin2d = new WebIFC.IFC4.IfcCartesianPoint([
      new WebIFC.IFC4.IfcLengthMeasure(0),
      new WebIFC.IFC4.IfcLengthMeasure(0)
    ]);
    ifcAPI.WriteLine(modelId, worldOrigin2d);

    const worldAxis2d = new WebIFC.IFC4.IfcAxis2Placement2D(worldOrigin2d, null);
    ifcAPI.WriteLine(modelId, worldAxis2d);

    const trueNorth = new WebIFC.IFC4.IfcDirection([
      new WebIFC.IFC4.IfcReal(0),
      new WebIFC.IFC4.IfcReal(1)
    ]);
    ifcAPI.WriteLine(modelId, trueNorth);

    const geomContext = new WebIFC.IFC4.IfcGeometricRepresentationContext(
      new WebIFC.IFC4.IfcLabel("3D"),
      new WebIFC.IFC4.IfcLabel("Model"),
      new WebIFC.IFC4.IfcDimensionCount(3),
      null,
      worldAxis2d,
      trueNorth
    );
    ifcAPI.WriteLine(modelId, geomContext);

    // -------------------------------------------------------------------------
    // Identity placement — shared by all elements with no explicit transform
    // -------------------------------------------------------------------------

    const identityOrigin = new WebIFC.IFC4.IfcCartesianPoint([
      new WebIFC.IFC4.IfcLengthMeasure(0),
      new WebIFC.IFC4.IfcLengthMeasure(0),
      new WebIFC.IFC4.IfcLengthMeasure(0)
    ]);
    ifcAPI.WriteLine(modelId, identityOrigin);

    const zAxis = new WebIFC.IFC4.IfcDirection([
      new WebIFC.IFC4.IfcReal(0),
      new WebIFC.IFC4.IfcReal(0),
      new WebIFC.IFC4.IfcReal(1)
    ]);
    ifcAPI.WriteLine(modelId, zAxis);

    const xAxis = new WebIFC.IFC4.IfcDirection([
      new WebIFC.IFC4.IfcReal(1),
      new WebIFC.IFC4.IfcReal(0),
      new WebIFC.IFC4.IfcReal(0)
    ]);
    ifcAPI.WriteLine(modelId, xAxis);

    const identityAP3D = new WebIFC.IFC4.IfcAxis2Placement3D(identityOrigin, zAxis, xAxis);
    ifcAPI.WriteLine(modelId, identityAP3D);

    const identityPlacement = new WebIFC.IFC4.IfcLocalPlacement(null, identityAP3D);
    ifcAPI.WriteLine(modelId, identityPlacement);

    // -------------------------------------------------------------------------
    // IfcProject
    // -------------------------------------------------------------------------

    const projectDataObjects = dataModel?.objectsByType?.["IfcProject"];
    const projectDataObject = projectDataObjects ? Object.values(projectDataObjects)[0] : null;

    const proj = new WebIFC.IFC4.IfcProject(
      new WebIFC.IFC4.IfcGloballyUniqueId(projectDataObject?.id || createUUID()),
      ownerHistory,
      new WebIFC.IFC4.IfcLabel(projectDataObject?.name || "Project"),
      projectDataObject?.description ? new WebIFC.IFC4.IfcText(projectDataObject.description) : null,
      null, null, null,
      [geomContext],
      unitAssign
    );
    ifcAPI.WriteLine(modelId, proj);

    // Map objectId → written IFC element (for relationship wiring)
    const ifcElementMap: { [id: string]: any } = {};
    if (projectDataObject) {
      ifcElementMap[projectDataObject.id] = proj;
    }

    // -------------------------------------------------------------------------
    // Build geometry for each SceneObject then write the DataObject element
    // -------------------------------------------------------------------------

    if (dataModel) {
      for (const objectId in dataModel.objects) {
        if (ifcElementMap[objectId]) continue; // already handled (IfcProject)

        const dataObject = dataModel.objects[objectId];
        const typeName = (dataObject.type || "IfcBuildingElementProxy") as string;
        const IfcClass = (<any>WebIFC.IFC4)[typeName];

        // Fall back to IfcBuildingElementProxy for types not in web-ifc — keeps
        // the object in ifcElementMap so relationship chains are not broken.
        const IfcClassResolved = IfcClass || WebIFC.IFC4.IfcBuildingElementProxy;

        const guid = new WebIFC.IFC4.IfcGloballyUniqueId(dataObject.id);
        const name = new WebIFC.IFC4.IfcLabel(dataObject.name || typeName);
        const desc = dataObject.description
          ? new WebIFC.IFC4.IfcText(dataObject.description)
          : null;

        // --- Geometry ---------------------------------------------------------
        // Vertices are baked into world space using each mesh's worldMatrix so
        // the element can use an identity IfcLocalPlacement.

        let representation: any = null;
        const sceneObject = sceneModel?.objects[objectId];

        if (sceneObject) {
          // One IfcTriangulatedFaceSet + IfcStyledItem per SceneMesh so that each
          // mesh keeps its own colour and opacity (e.g. opaque frame + transparent
          // glass pane in the same IfcWindow object).
          const repItems: any[] = [];

          for (const mesh of sceneObject.meshes) {
            const geometry = mesh.geometry;
            if (!geometry.indices || geometry.indices.length === 0) continue;

            const posComp  = geometry.positionsCompressed;
            const aabb     = geometry.aabb;
            const matrix   = mesh.worldMatrix;
            const numVerts = posComp.length / 3;

            const coordList: any[][]    = [];
            const coordIndex: number[][] = [];

            for (let i = 0; i < numVerts; i++) {
              _compressedPos[0] = posComp[i * 3];
              _compressedPos[1] = posComp[i * 3 + 1];
              _compressedPos[2] = posComp[i * 3 + 2];
              decompressPoint3WithAABB3(_compressedPos, aabb, _decompressedPos);

              // Apply world matrix (column-major):  p' = M * p
              const lx = _decompressedPos[0];
              const ly = _decompressedPos[1];
              const lz = _decompressedPos[2];
              coordList.push([
                new WebIFC.IFC4.IfcLengthMeasure(matrix[0]*lx + matrix[4]*ly + matrix[8]*lz  + matrix[12]),
                new WebIFC.IFC4.IfcLengthMeasure(matrix[1]*lx + matrix[5]*ly + matrix[9]*lz  + matrix[13]),
                new WebIFC.IFC4.IfcLengthMeasure(matrix[2]*lx + matrix[6]*ly + matrix[10]*lz + matrix[14])
              ]);
            }

            const idx = geometry.indices;
            for (let i = 0, len = idx.length; i < len; i += 3) {
              coordIndex.push([idx[i] + 1, idx[i + 1] + 1, idx[i + 2] + 1]); // 1-based
            }

            if (coordList.length === 0) continue;

            const pts = new WebIFC.IFC4.IfcCartesianPointList3D(<any>coordList);
            ifcAPI.WriteLine(modelId, pts);

            const tfs = new WebIFC.IFC4.IfcTriangulatedFaceSet(
              pts, null, null, <any>coordIndex, null
            );
            ifcAPI.WriteLine(modelId, tfs);

            // Per-mesh colour and opacity
            const col   = mesh.effectiveColor;
            const alpha = mesh.effectiveOpacity;

            const rgb = new WebIFC.IFC4.IfcColourRgb(
              null,
              new WebIFC.IFC4.IfcNormalisedRatioMeasure(col[0]),
              new WebIFC.IFC4.IfcNormalisedRatioMeasure(col[1]),
              new WebIFC.IFC4.IfcNormalisedRatioMeasure(col[2])
            );
            ifcAPI.WriteLine(modelId, rgb);

            const surfaceRendering = new WebIFC.IFC4.IfcSurfaceStyleRendering(
              rgb,
              alpha < 1 ? new WebIFC.IFC4.IfcNormalisedRatioMeasure(1 - alpha) : null,
              null, null, null, null, null, null, null
            );
            ifcAPI.WriteLine(modelId, surfaceRendering);

            const surfaceStyle = new WebIFC.IFC4.IfcSurfaceStyle(null, null, [surfaceRendering]);
            ifcAPI.WriteLine(modelId, surfaceStyle);

            ifcAPI.WriteLine(modelId, new WebIFC.IFC4.IfcStyledItem(tfs, [surfaceStyle], null));

            repItems.push(tfs);
          }

          if (repItems.length > 0) {
            const shapeRep = new WebIFC.IFC4.IfcShapeRepresentation(
              geomContext,
              new WebIFC.IFC4.IfcLabel("Body"),
              new WebIFC.IFC4.IfcLabel("Tessellation"),
              repItems
            );
            ifcAPI.WriteLine(modelId, shapeRep);

            representation = new WebIFC.IFC4.IfcProductDefinitionShape(null, null, [shapeRep]);
            ifcAPI.WriteLine(modelId, representation);
          }
        }

        // --- IFC element ------------------------------------------------------
        // Spatial structure elements need specific constructor signatures.
        // Physical elements (walls, slabs, columns, …) share the standard
        // 9-parameter IfcElement signature.

        let ifcElement: any;

        if (typeName === "IfcSite") {
          ifcElement = new WebIFC.IFC4.IfcSite(
            guid, ownerHistory, name, desc, null,
            identityPlacement, representation,
            null, null, null, null, null, null, null
          );
        } else if (typeName === "IfcBuilding") {
          ifcElement = new WebIFC.IFC4.IfcBuilding(
            guid, ownerHistory, name, desc, null,
            identityPlacement, representation,
            null, null, null, null, null
          );
        } else if (typeName === "IfcBuildingStorey") {
          ifcElement = new WebIFC.IFC4.IfcBuildingStorey(
            guid, ownerHistory, name, desc, null,
            identityPlacement, representation,
            null, null, null
          );
        } else if (typeName === "IfcSpace") {
          ifcElement = new WebIFC.IFC4.IfcSpace(
            guid, ownerHistory, name, desc, null,
            identityPlacement, representation,
            null, null, null, null
          );
        } else {
          // Standard IfcElement subclass:
          // GlobalId, OwnerHistory, Name, Description, ObjectType,
          // ObjectPlacement, Representation, Tag, PredefinedType
          try {
            ifcElement = new IfcClassResolved(
              guid, ownerHistory, name, desc, null,
              representation ? identityPlacement : null,
              representation,
              null, null
            );
          } catch (_) {
            ifcElement = new WebIFC.IFC4.IfcBuildingElementProxy(
              guid, ownerHistory, name, desc, null,
              representation ? identityPlacement : null,
              representation,
              null, null
            );
          }
        }

        ifcAPI.WriteLine(modelId, ifcElement);
        ifcElementMap[objectId] = ifcElement;

        // --- Property sets ----------------------------------------------------

        if (dataObject.propertySets?.length) {
          for (const propSet of dataObject.propertySets) {
            const ifcProperties = propSet.properties.map(p => {
              const val = new WebIFC.IFC4.IfcPropertySingleValue(
                new WebIFC.IFC4.IfcIdentifier(p.name),
                p.description ? new WebIFC.IFC4.IfcText(p.description) : null,
                p.value !== undefined ? new WebIFC.IFC4.IfcLabel(String(p.value)) : null,
                null
              );
              ifcAPI.WriteLine(modelId, val);
              return val;
            });

            const ifcPSet = new WebIFC.IFC4.IfcPropertySet(
              new WebIFC.IFC4.IfcGloballyUniqueId(propSet.id || createUUID()),
              ownerHistory,
              new WebIFC.IFC4.IfcLabel(propSet.name || "PropertySet"),
              null,
              ifcProperties
            );
            ifcAPI.WriteLine(modelId, ifcPSet);

            const relDef = new WebIFC.IFC4.IfcRelDefinesByProperties(
              new WebIFC.IFC4.IfcGloballyUniqueId(createUUID()),
              ownerHistory,
              null, null,
              [ifcElement],
              ifcPSet
            );
            ifcAPI.WriteLine(modelId, relDef);
          }
        }
      }
    }

    // -------------------------------------------------------------------------
    // Relationships
    //
    // DataModel stores 1-to-1 Relationships; IFC relationships are 1-to-many.
    // Group by (type, relatingObjectId) so we emit one IFC rel per group.
    // -------------------------------------------------------------------------

    if (dataModel) {
      type RelGroup = { type: string; relatingId: string; relatedIds: string[] };
      const relGroups: { [key: string]: RelGroup } = {};

      for (const rel of dataModel.relationships) {
        const key = `${rel.type}|${rel.relatingObject.id}`;
        if (!relGroups[key]) {
          relGroups[key] = {type: rel.type, relatingId: rel.relatingObject.id, relatedIds: []};
        }
        relGroups[key].relatedIds.push(rel.relatedObject.id);
      }

      for (const key in relGroups) {
        const group = relGroups[key];
        const relatingEl = ifcElementMap[group.relatingId];
        if (!relatingEl) continue;

        const relatedEls = group.relatedIds
          .map(id => ifcElementMap[id])
          .filter(Boolean);
        if (relatedEls.length === 0) continue;

        const relGuid = new WebIFC.IFC4.IfcGloballyUniqueId(createUUID());
        const relLabel = new WebIFC.IFC4.IfcLabel(group.type);

        if (group.type === "IfcRelAggregates") {
          // (GlobalId, OwnerHistory, Name, Description, RelatingObject, RelatedObjects)
          ifcAPI.WriteLine(modelId, new WebIFC.IFC4.IfcRelAggregates(
            relGuid, ownerHistory, relLabel, null,
            relatingEl, relatedEls
          ));
        } else if (group.type === "IfcRelContainedInSpatialStructure") {
          // (GlobalId, OwnerHistory, Name, Description, RelatedElements, RelatingStructure)
          ifcAPI.WriteLine(modelId, new WebIFC.IFC4.IfcRelContainedInSpatialStructure(
            relGuid, ownerHistory, relLabel, null,
            relatedEls, relatingEl
          ));
        } else {
          // Best-effort for other relationship types: try the same 6-param pattern.
          const IfcRelClass = (<any>WebIFC.IFC4)[group.type];
          if (IfcRelClass) {
            try {
              ifcAPI.WriteLine(modelId, new IfcRelClass(
                relGuid, ownerHistory, relLabel, null,
                relatingEl, relatedEls
              ));
            } catch (_) {
              // Skip relationship types whose constructor doesn't fit the pattern
            }
          }
        }
      }
    }

    resolve(ifcAPI.SaveModel(modelId));
  });
}
