/**
 * Provides info on the [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#dtx) generated by xeokit-convert.
 *
 * See {@link "@xeokit/dtx"} for usage.
 */
export const DTX_INFO = {

    /**
     * The [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#dtx) version generated by xeokit-convert.
     *
     * @property dtxVersion
     * @type {number}
     */
    dtxVersion: 11
};