/**
 * Provides info on the [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#dtx) generated by {@link @xeokit/dtx!saveDTX}.
 *
 * See {@link "@xeokit/dtx" | @xeokit/dtx} for usage.
 */
export const DTX_INFO = {

    /**
     * The [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#dtx) version generated by {@link @xeokit/dtx!saveDTX}.
     *
     * @property dtxVersion
     * @type {number}
     */
    dtxVersion: 1
};
