import {apply, createUUID} from "../utils";
import {SDKErrorType, type SDKResult} from "../core";
import {Scene, SceneMesh, SceneObject} from "../scene";
import {View} from "./View";
import type {ViewerParams} from "./ViewerParams";
import type {ViewParams} from "./ViewParams";
import {ViewerEvents} from "./ViewerEvents";

/**
 * 3D model viewer.
 *
 * See {@link viewer | "@xeokit/sdk/viewer" } for usage.
 */
export class Viewer {

  /**
   * ID of this Viewer.
   */
  declare id: string;

  /**
   * True once this Viewer has been destroyed.
   *
   * Don't use this Viewer if this is ````false````.
   */
  declare destroyed: boolean;

  /**
   * The events emitted by this Viewer.
   */
  readonly events: ViewerEvents;

  /**
   * The Viewer's scene representation.
   *
   * The {@link scene!SceneModel | SceneModels} is the container of {@link scene!SceneModel | SceneModels}
   * and {@link scene!SceneObject | SceneObjects}, which contain the geometry and materials for models currently
   * loaded in the Viewer.
   */
  scene: Scene;

  /**
   * Map of all the Views in this Viewer.
   *
   * Each {@link View} is mapped here against {@link View.id | View.id}.
   *
   * Each {@link View} is an independently configurable view of the Viewer's models, with its own
   * canvas, camera position, section planes, lights, and object visual states.
   */
  readonly views: { [key: string]: View };

  /**
   * List of all the Views in this Viewer.
   *
   * Each {@link View} is an independently configurable view of the Viewer's models, with its own canvas, camera position, section planes, lights, and object visual states.
   *
   * @internal
   */
  readonly viewList: View[];

  /**
   *  The number of {@link View | Views} belonging to this Viewer.
   */
  numViews: number;

  /**
   * Enables or disables error logging to the console for this Viewer.
   *
   * Default value is ````false````.
   */
  public logging: boolean = false;

  private _onSceneObjectCreated: () => void;
  private _onSceneObjectDestroyed: () => void;
  private _onSceneDestroyed: () => void;
  private _onSceneMeshMatrixChanged: () => void;
  private _onSceneMeshColorChanged: () => void;

  /**
   * Creates a Viewer.
   *
   * @param params - Viewer configuration.
   * @param params.scene - Contains model representations. The same Scene can be attached to any number of Viewers.
   * @param params.id - ID for this Viewer, automatically generated by default.
   * @param params.logging - Enables or disables error logging to the console for this Viewer. Default value is ````false````.
   */
  constructor(params?: {
    scene?: Scene,
    id?: string,
    logging?: boolean
  }) {
    this.id = params?.id || createUUID();
    this.events = new ViewerEvents();
    this.viewList = [];
    this.numViews = 0;
    this.views = {};
    this.destroyed = false;
    this.logging = !!params?.logging;
    if (params?.scene) {
      this.attachScene(params.scene);
    }
  }

  /**
   * Attaches a {@link Scene} to this Viewer.
   *
   * * Creates {@link ViewObject | ViewObjects} in each existing {@link View} for all {@link SceneObject | SceneObjects} in the attached {@link Scene}.
   * * Subscribes to {@link Scene.events.onSceneObjectCreated | Scene.events.onSceneObjectCreated} and {@link Scene.events.onSceneObjectDestroyed | Scene.events.onSceneObjectDestroyed} events to create and destroy {@link ViewObject | ViewObjects} in each existing {@link View} as {@link SceneObject | SceneObjects} are created and destroyed in the attached {@link Scene}.
   *
   * @param scene - The Scene to show.
   * @param scene
   */
  public attachScene(scene: Scene): SDKResult<Viewer> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.attachScene] Viewer has been destroyed."
      });
    }
    if (this.scene === scene) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.attachScene] Scene already attached."
      });
    }
    if (scene.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.attachScene] Scene has been destroyed."
      });
    }
    if (this.scene) {
      this.detachScene();
    }
    this.scene = scene;
    for (const sceneObjectId in this.scene.objects) {
      const sceneObject = this.scene.objects[sceneObjectId];
      this._attachSceneObject(sceneObject);
    }
    this._onSceneDestroyed = this.scene.events.onSceneDestroyed.subscribe(() => {
      this.detachScene();
    });
    this._onSceneObjectCreated = this.scene.events.onSceneObjectCreated.subscribe((scene: Scene, sceneObject: SceneObject) => {
      this._attachSceneObject(sceneObject);
    });
    this._onSceneObjectDestroyed = this.scene.events.onSceneObjectDestroyed.subscribe((scene: Scene, sceneObject: SceneObject) => {
      this._detachSceneObject(sceneObject);
    });
    // also listen for mesh matrix changes

    const sceneMeshUpdated = (scene: Scene, mesh: SceneMesh) => {
      for (const viewId in this.views) {
        const view = this.views[viewId];
        view.needsRender();
      }
    };

    this._onSceneMeshMatrixChanged = this.scene.events.onSceneMeshMatrixChanged.subscribe(sceneMeshUpdated);
    this._onSceneMeshColorChanged = this.scene.events.onSceneMeshColorChanged.subscribe(sceneMeshUpdated);

    this.events.onSceneAttached.dispatch(this, scene);
    return {
      ok: true,
      value: this
    };
  }

  private _attachSceneObject(sceneObject: SceneObject) {
    for (const viewId in this.views) {
      const view = this.views[viewId];
      view._attachSceneObject(sceneObject);
    }
  }

  private _detachSceneObject(sceneObject: SceneObject) {
    for (const viewId in this.views) {
      const view = this.views[viewId];
      view._detachSceneObject(sceneObject);
    }
  }

  /**
   * Detaches the currently attached {@link Scene} from this Viewer.
   *
   * * Destroys all {@link ViewObject | ViewObjects} in each existing {@link View} that were created for {@link SceneObject | SceneObjects} in the detached {@link Scene}.
   * * Unsubscribes from {@link Scene.events.onSceneObjectCreated | Scene.events.onSceneObjectCreated} and {@link Scene.events.onSceneObjectDestroyed | Scene.events.onSceneObjectDestroyed} events of the detached {@link Scene}.
   */
  public detachScene(): SDKResult<Viewer> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.detachScene] Viewer has been destroyed."
      });
    }
    if (!this.scene) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.detachScene] No Scene attached."
      });
    }
    for (const sceneObjectId in this.scene.objects) {
      const sceneObject = this.scene.objects[sceneObjectId];
      this._detachSceneObject(sceneObject);
    }
    this.scene.events.onSceneDestroyed.unsubscribe(this._onSceneDestroyed);
    this.scene.events.onSceneObjectCreated.unsubscribe(this._onSceneObjectCreated);
    this.scene.events.onSceneObjectDestroyed.unsubscribe(this._onSceneObjectDestroyed);
    const scene = this.scene;
    this.scene = null;
    this.events.onSceneDetached.dispatch(this, scene);
    return {
      ok: true,
      value: this
    };
  }

  /**
   * Creates a new {@link View} within this Viewer.
   *
   * * To destroy the View after use, call {@link View.destroy}.
   *
   * ### Usage
   *
   * ````typescript
   * const viewResult = myViewer.createView({
   *      id: "myView",
   *      elementId: "myView1"
   * });
   *
   * if (!viewResult.ok) {
   *      console.error(viewResult.error);
   * } else {
   *      const view = viewResult.value;
   *      view.camera.eye = [-3.933, 2.855, 27.018];
   *      view.camera.look = [4.400, 3.724, 8.899];
   *      view.camera.up = [-0.018, 0.999, 0.039];
   *
   *      //...
   * }
   * ````
   *
   * @param viewParams - View configuration.
   * @returns A result containing the created {@link View} on success, or an error message on failure.
   */
  createView(viewParams: ViewParams): SDKResult<View> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.createView] Viewer has been destroyed."
      });
    }
    const viewId = viewParams.id || createUUID();
    if (this.views[viewId]) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidInput,
        error: `[Viewer.createView] A View with ID "${viewId}" already exists.`
      });
    }
    if (!viewParams.elementId && !viewParams.htmlElement) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidInput,
        error: `[Viewer.createView] Must provide either elementId or htmlElement in viewParams.`
      });
    }
    if (viewParams.elementId) {
      const htmlElement = document.getElementById(viewParams.elementId);
      if (!(htmlElement instanceof HTMLElement)) {
        return this.logError({
          ok: false,
          type: SDKErrorType.InvalidInput,
          error: `[Viewer.createView] The elementId "${viewParams.elementId}" does not reference a valid HTMLElement.`
        });
      }
    }
    if (viewParams.htmlElement) {
      if (!(viewParams.htmlElement instanceof HTMLElement)) {
        return this.logError({
          ok: false,
          type: SDKErrorType.InvalidInput,
          error: `[Viewer.createView] The provided htmlElement is not a valid HTMLElement.`
        });
      }
    }
    if (viewParams.backgroundColor) {
      const bgColor = viewParams.backgroundColor;
      if (bgColor.length < 3) {
        return this.logError({
          ok: false,
          type: SDKErrorType.InvalidInput,
          error: `[Viewer.createView] The provided backgroundColor must have at least three elements for R, G, and B.`
        });
      }
      for (let i = 0; i < 3; i++) {
        const c = bgColor[i];
        if (c < 0 || c > 1) {
          return this.logError({
            ok: false,
            type: SDKErrorType.InvalidInput,
            error: `[Viewer.createView] The provided backgroundColor elements must be in range [0..1].`
          });
        }
      }
    }
    const view = new View(this, apply({id: viewId}, viewParams));
    this._attachView(view);
    if (this.scene) {
      for (const sceneObjectId in this.scene.objects) {
        const sceneObject = this.scene.objects[sceneObjectId];
        view._attachSceneObject(sceneObject);
      }
    }
    this.events.onViewCreated.dispatch(this, view);
    return {
      ok: true,
      value: view
    };
  }

  /**
   * Called by a {@link View} when it is destroyed.
   * @private
   */
  _destroyView(view: View): void {
    this._detachView(view);
    this.events.onViewDestroyed.dispatch(this, view);
  }

  /**
   * Trigger needsRender of all {@link View | Views} belonging to this Viewer.
   *
   * @private
   */
  needsRender(): void {
    for (const viewId in this.views) {
      this.views[viewId].needsRender();
    }
  }

  /**
   * Clears this Viewer.
   *
   * Destroys all existing {@link View | Views} and resets all properties to their default values.
   */
  clear(): SDKResult<void> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.clear] Viewer already destroyed"
      });
    }
    for (const viewId in this.views) {
      const view = this.views[viewId];
      view.destroy();
    }
    return {
      ok: true,
      value: undefined
    };
  }

 private _attachView(view: View): void {
    if (this.views[view.id]) {
      return;
    }
    this.views[view.id] = view;
    for (let viewIndex = 0; ; viewIndex++) {
      if (!this.viewList[viewIndex]) {
        this.viewList[viewIndex] = view;
        this.numViews++;
        view.viewIndex = viewIndex;
        return;
      }
    }
  }

  private _detachView(view: View): void {
    if (!this.views[view.id]) {
      return;
    }
    delete this.views[view.id];
    delete this.viewList[view.viewIndex];
    this.numViews--;
  }

  /**
   * Configures this Viewer.
   *
   * @param viewerParams
   */
  fromParams(viewerParams: ViewerParams): SDKResult<void> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.fromParams] Viewer already destroyed"
      });
    }
    if (viewerParams.views) {
      for (const viewParams of viewerParams.views) {
        if (viewParams.id !== undefined) {
          const existingView = this.views[viewParams.id];
          if (existingView) {
            const result = existingView.fromParams(viewParams); // Update existing View
            if (result.ok === false) {
              return result; // Already logged
            }
          } else {
            const result = this.createView(viewParams);
            if (result.ok === false) {
              return result; // Already logged
            }
          }
        } else {
          const result = this.createView(viewParams);
          if (result.ok === false) {
            return result; // Already logged
          }
        }
      }
    }
    return {
      ok: true,
      value: undefined
    };
  }

  /**
   * Gets the current configuration of this Viewer.
   */
  toParams(): SDKResult<any> {
    if (this.destroyed) {
      return this.logError({
        ok: false,
        type: SDKErrorType.InvalidOperation,
        error: "[Viewer.toParams] Viewer already destroyed"
      });
    }
    const params = {
      views: []
    };
    this.viewList.map(el => el.toParams())
    for (let i = 0; i < this.numViews; i++) {
      const view = this.viewList[i];
      if (view) {
        const viewParamsResult = view.toParams();
        if (viewParamsResult.ok === false) {
          return viewParamsResult; // Already logged
        }
        params.views.push(viewParamsResult.value);
      }
    }
    return {
      ok: true,
      value: params
    };
  }

  /**
   * Logs an error via the Viewer's {@link ViewerEvents.onError | ViewerEvents.onError} event.
   * @private
   * @param result
   */
  logError(result: SDKResult<any>): SDKResult<any> {
    if (result.ok === false) {
      if (this.logging) {
        console.error(`[xeokit Viewer] ${result.error}`);
      }
      this.events.onError.dispatch(this, result);
    }
    return result;
  }

  /**
   * Destroys this Viewer.
   */
  destroy(): void {
    if (this.destroyed) {
      return;
    }
    this.destroyed = true;
    for (const id in this.views) {
      this.views[id].destroy();
    }
    this.events.onViewerDestroyed.dispatch(this, false);
    this.events.destroy();
  }


}
