/**
 * Provides info on the [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) generated by xeokit-convert.
 *
 * See {@link "@xeokit/xkt"} for usage.
 */
export const XKT_INFO = {

    /**
     * The [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) version generated by xeokit-convert.
     *
     * @property xktVersion
     * @type {number}
     */
    xktVersion: 11
};