import {type ModelConverterReporter} from "../ModelConverterReporter";
import {type ModelConverterStatsReport} from "./ModelConverterStatsReport";
import {type ModelConverterResult} from "../../ModelConverterResult";

/**
 * Generates a detailed report on the model conversion process, including statistics
 * about the input, output, scene models, and data models.
 *
 * This report captures metadata about the conversion, such as the command run, the pipeline used,
 * and specific details about the inputs and outputs.
 *
 * @returns A populated {@link ModelConverterStatsReport | ModelConverterStatsReport} containing conversion statistics.
 */
export const createStatsReport: ModelConverterReporter = (pipelineResult: ModelConverterResult): ModelConverterStatsReport => {

  const pipelineStatsReport: ModelConverterStatsReport = {
    description: "Generated by @xeokit/sdk/conversion/pipeline/createStatsReport",
    command: "",//`node xeoconvert.js ${process.argv.slice(2).join(' ')}`, // TODO
    time: (new Date()).toISOString(), // "2025-04-23T18:30:00.000Z"
    pipeline: pipelineResult.pipeline,
    inputs: {},
    sceneModels: {},
    dataModels: {},
    outputs: {},
    errors: pipelineResult.errors
  };

  for (const inputId in pipelineResult.inputs) {
    const input = pipelineResult.inputs[inputId];
    pipelineStatsReport.inputs[inputId] = {
      filePath: input.filePath,
      fileFormat: input.fileFormat,
      fileFormatVersion: input.fileFormatVersion,
      fileDataSizeBytes: input.fileDataSizeBytes,
      fileDataType: input.fileDataType,
      options: input.options,
      sceneModel: input.sceneModel,
      dataModel: input.dataModel,
      messages: input.messages,
      warnings: input.warnings,
      errors: input.errors
    };
  }

  for (const sceneModelId in pipelineResult.scene.models) {
    const sceneModel = pipelineResult.scene.models[sceneModelId];
    pipelineStatsReport.sceneModels[sceneModelId] = sceneModel.stats;
  }

  for (const dataModelId in pipelineResult.data.models) {
    const dataModel = pipelineResult.data.models[dataModelId];
    pipelineStatsReport.dataModels[dataModelId] = dataModel.stats;
  }

  for (const outputId in pipelineResult.outputs) {
    const output = pipelineResult.outputs[outputId];
    pipelineStatsReport.outputs[outputId] = {
      filePath: output.filePath,
      fileFormat: output.fileFormat,
      fileFormatVersion: output.fileFormatVersion,
      fileDataSizeBytes: output.fileDataSizeBytes,
      fileDataType: output.fileDataType,
      options: output.options,
      sceneModel: output.sceneModel,
      dataModel: output.dataModel,
      messages: output.messages,
      warnings: output.warnings,
      errors: output.errors
    };
  }

  return pipelineStatsReport;
}
