/**
 * Provides info on the [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) generated by {@link xkt!saveXKT}.
 *
 * See {@link "xkt" | @xeokit/xkt} for usage.
 */
export declare const XKT_INFO: {
    /**
     * The [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) version generated by {@link xkt!saveXKT}.
     *
     * @property xktVersion
     * @type {number}
     */
    xktVersion: number;
};
//# sourceMappingURL=XKT_INFO.d.ts.map