window.PROCEDURAL_CITY_STREAM_CONFIG = {
  "indexUrl": "../../models/ProceduralCityAmsterdam/xgfstream/index.runtime.json",
  "metadataUrl": "../../models/ProceduralCityAmsterdam/metadata.json",
  "reportUrl": "../../models/ProceduralCityAmsterdam/report.json",
  "modelId": "ProceduralCityAmsterdam",
  "viewId": "proceduralCityAmsterdamView",
  "streamLabel": "Amsterdam procedural city",
  "windSound": true,
  "vehicle": {
    "modelUrl": "../../models/SpaceShip/xgf/model.xgf",
    "modelId": "SpaceShip",
    "scale": 0.0085,
    "sourceCenter": [
      0.0001430511474609375,
      290.83030990186523,
      -245.64296573058726
    ],
    "forwardAxis": "-Y",
    "cameraDistance": 24,
    "cameraHeight": 7.2,
    "cameraLookAhead": 13,
    "cameraLookHeight": 1.6,
    "cameraFollowSmoothing": 4.8,
    "cameraLookSmoothing": 9,
    "cameraLateralOffset": 0,
    "cameraTrailFollow": 0.65,
    "cameraTrailHeight": 1.4,
    "shipMouseDragYawSensitivity": 0.0095,
    "shipMouseDragPitchSensitivity": 0.0068,
    "shipMouseDragResponse": 5.2,
    "maxShipMouseDragInputPerFrame": 0.7,
    "shipKeyYawInitialScale": 0.34,
    "shipKeyYawRampSeconds": 1.45,
    "shipYawRateDegreesPerSecond": 76,
    "shipPitchRateDegreesPerSecond": 58,
    "maxShipPitchDegrees": 56,
    "minShipPitchDegrees": -42,
    "maxVisualRollDegrees": 46,
    "rollSmoothing": 7.5,
    "collision": true,
    "bodyRadius": 4,
    "minAltitude": 6,
    "exhaustPlume": {
      "offset": [0, 4.25, 0.18],
      "trailLength": 44,
      "trailSegments": 16,
      "trailAdvection": 0,
      "trailTether": 0,
      "trailExpansion": 1,
      "trailOpacity": 0.6,
      "radius": 0.78,
      "wander": 0.16,
      "radialSegments": 6
    },
    "minForwardSpeed": 26,
    "maxForwardSpeed": 175,
    "acceleration": 74,
    "brakeDeceleration": 54,
    "coastDeceleration": 1.2,
    "startSpeed": 44,
    "initialCamera": {
      "eye": [-360, -520, 118],
      "look": [-260, -390, 72],
      "up": [0, 0, 1],
      "fov": 62
    }
  }
};

import("../formats_xgf_proceduralCity/index.js");
