import {apply, createUUID, inQuotes} from "@xeokit/utils";
import {type Capabilities, Component, EventEmitter, SDKError} from "@xeokit/core";
import {EventDispatcher} from "strongly-typed-events";
import type {FloatArrayParam} from "@xeokit/math";
import {Scene, SceneModel} from "@xeokit/scene";

import {View} from "./View";
import {scheduler} from "./scheduler";
import type {Renderer} from "./Renderer";

import type {ViewParams} from "./ViewParams";

class TickParams {
}

/**
 * A Browser-based 2D/3D model viewer.
 *
 * See {@link @xeokit/viewer} for usage.
 */
export class Viewer extends Component {

    /**
     ID of this Viewer.
     */
    declare readonly id: string;

    /**
     True once this Viewer has been destroyed.

     Don't use this Viewer if this is ````false````.
     */
    declare readonly destroyed: boolean;

    /**
     * Indicates the capabilities of this Viewer.
     */
    readonly capabilities: Capabilities;

    /**
     * Emits an event each time a message is logged.
     *
     * @event
     */
    readonly onLog: EventEmitter<Viewer, string>;

    /**
     * Emits an event each time a Viewer "tick" occurs (~10-60 times per second).
     *
     * @event
     */
    readonly onTick: EventEmitter<Viewer, TickParams>;

    /**
     * Emits an event each time a {@link @xeokit/viewer!View} is created.
     *
     * @event
     */
    readonly onViewCreated: EventEmitter<Viewer, View>;

    /**
     * Emits an event each time a {@link @xeokit/viewer!View} is destroyed.
     *
     * @event
     */
    readonly onViewDestroyed: EventEmitter<Viewer, View>;

    /**
     * The Viewer's scene representation.
     */
    readonly scene: Scene;

    /**
     * Map of all the Views in this Viewer.
     *
     * Each {@link @xeokit/viewer!View} is an independently configurable view of the Viewer's models, with its own canvas, camera position, section planes, lights, and object visual states.
     */
    readonly views: { [key: string]: View };

    /**
     * List of all the Views in this Viewer.
     *
     * Each {@link @xeokit/viewer!View} is an independently configurable view of the Viewer's models, with its own canvas, camera position, section planes, lights, and object visual states.
     */
    readonly viewList: View[];

    /**
     *  The number of {@link View | Views} belonging to this Viewer.
     */
    numViews: number;

    /**
     The time that this Viewer was created.
     */
    readonly startTime: number = (new Date()).getTime();

    /**
     * @private
     */
    readonly renderer: Renderer;

    /**
     Creates a Viewer.

     @param params - Viewer configuration.
     @param params.scene - Contains model representations.
     @param params.renderer - Manages rendering of models.
     @param params.id - ID for this Viewer, automatically generated by default.
     @param params.units - The measurement unit type. Accepted values are ````"meters"````, ````"metres"````, , ````"centimeters"````, ````"centimetres"````, ````"millimeters"````,  ````"millimetres"````, ````"yards"````, ````"feet"```` and ````"inches"````.
     @param params.scale - The number of Real-space units in each World-space coordinate system unit.
     @param params.origin - The Real-space 3D origin, in current measurement units, at which the World-space coordinate origin ````[0,0,0]```` sits.
     @param params.localeService - Locale-based translation service.

     */
    constructor(params: {
        scene?: Scene,
        renderer: Renderer,
        id?: string,
        units?: string,
        scale?: number,
        origin?: FloatArrayParam,
    }) {
        super(null, {});

        this.onLog = new EventEmitter(new EventDispatcher<Viewer, string>());
        this.onTick = new EventEmitter(new EventDispatcher<Viewer, TickParams>());
        this.onViewCreated = new EventEmitter(new EventDispatcher<Viewer, View>());
        this.onViewDestroyed = new EventEmitter(new EventDispatcher<Viewer, View>());

        this.id = params.id || createUUID();

        this.viewList = [];
        this.numViews = 0;
        this.views = {};
        this.destroyed = false;

        this.capabilities = {
            maxViews: 1,
            headless: false,
            astcSupported: false,
            etc1Supported: false,
            etc2Supported: false,
            dxtSupported: false,
            bptcSupported: false,
            pvrtcSupported: false
        };

        this.scene = params.scene || new Scene();

        this.renderer = params.renderer;

        this.renderer.getCapabilities(this.capabilities);

        this.renderer.attachViewer(this);

        scheduler.registerViewer(this);
    }

    /**
     * Creates a new {@link @xeokit/viewer!View} within this Viewer.
     *
     * * The maximum number of views you're allowed to create is provided in {@link Capabilities.maxViews}. This
     * will be determined by the {@link Renderer} implementation the Viewer is configured with.
     * * To destroy the View after use, call {@link View.destroy}.
     * * You must add a View to the Viewer before you can create or load content into the Viewer's Viewer.
     *
     * ### Usage
     *
     * ````javascript
     * const view1 = myViewer.createView({
     *      id: "myView",
     *      canvasId: "myView1"
     *  });
     *
     * if (view1 instanceof SDKError) {
     *      console.log(view1.message);
     * } else {
     *      view1.camera.eye = [-3.933, 2.855, 27.018];
     *      view1.camera.look = [4.400, 3.724, 8.899];
     *      view1.camera.up = [-0.018, 0.999, 0.039];
     *
     *      //...
     * }
     * ````
     *
     * @param params View configuration.
     * @returns *{@link View}*
     * * On success.
     * @returns *{@link @xeokit/core!SDKError}*
     * * If View already exists with the given ID.
     * * Attempted to create too many Views - see {@link Capabilities.maxViews | Capabilities.maxViews}.
     */
    createView(params: ViewParams): View | SDKError {
        if (this.viewList.length >= this.capabilities.maxViews) {
            return new SDKError(`Attempted to create too many Views with View.createView() - maximum of ${this.capabilities.maxViews} is allowed`);
        }
        let viewId = params.id || createUUID();
        if (this.views[viewId]) {
            return new SDKError(`View with ID "${viewId}" already exists`);
        }
        // @ts-ignore
        const canvasElement = params.canvasElement || document.getElementById(params.canvasId);
        if (!(canvasElement instanceof HTMLCanvasElement)) {
            return new SDKError("Mandatory View config expected: valid canvasId or canvasElement");
        }
        const view = new View(apply({viewId, viewer: this}, params));
        this.#registerView(view);
        // Renderer.attachView sets up internal Renderer resources
        // that are expected by Renderer.attachSceneModel
        {
            const result: any = this.renderer.attachView(view);
            if (result instanceof SDKError) {
                return result;
            } else {
                view.viewIndex = result;
            }
        }
        view.onDestroyed.one(() => {
            this.#deregisterView(view);
            this.renderer.detachView(view.viewIndex);
            this.onViewDestroyed.dispatch(this, view);
        });
        // Renderer.attachSceneModel creates RendererViewObjects in Renderer.rendererViewObjects,
        // which are then expected by View.initViewObjects
        // TODO: assumes one View
        this.scene.onModelCreated.subscribe((scene: Scene, sceneModel: SceneModel) => {
            this.renderer.attachSceneModel(sceneModel);
        });
        this.scene.onModelDestroyed.subscribe((scene: Scene, sceneModel: SceneModel) => {
            this.renderer.detachSceneModel(sceneModel);
        });
        for (let id in this.scene.models) {
            this.renderer.attachSceneModel(this.scene.models[id]);
        }
        view.initViewObjects();
        this.onViewCreated.dispatch(this, view);
        this.log(`View created: ${view.viewId}`);
        return view;
    }

    /**
     * Trigger redraw of all {@link View | Views} belonging to this Viewer.
     *
     * @private
     */
    redraw(): void {
        for (let viewId in this.views) {
            this.views[viewId].redraw();
        }
    }

    /**
     * Logs a console debugging message for this Viewer.
     *
     * The console message will have this format: *````[LOG] [<component type> <component id>: <message>````*
     *
     * @private
     * @param message - The message to log
     */
    log(message: string): void {
        message = `[LOG] ${this.#prefixMessageWithID(message)}`;
        window.console.log(message);
    }

    /**
     * Logs a warning for this Viewer to the JavaScript console.
     *
     * The console message will have this format: *````[WARN] [<component type> =<component id>: <message>````*
     *
     * @private
     * @param message - The warning message to log
     */
    warn(message: string): void {
        message = `[WARN] ${this.#prefixMessageWithID(message)}`;
        window.console.warn(message);
    }

    /**
     * Logs an error for this Viewer to the JavaScript console.
     *
     * The console message will have this format: *````[ERROR] [<component type> =<component id>: <message>````*
     *
     * @private
     * @param message The error message to log
     */
    error(message: string): void {
        message = `[ERROR] ${this.#prefixMessageWithID(message)}`;
        window.console.error(message);
    }

    /**
     * Destroys this Viewer and all {@link View | Views} and {@link Plugin}s we've created within it.
     */
    destroy(): void {
        if (this.destroyed) {
            return;
        }
        scheduler.deregisterViewer(this);
        for (let id in this.views) {
            this.views[id].destroy();
        }
        this.onTick.clear();
        this.onViewCreated.clear();
        this.onViewDestroyed.clear();
    }

    /**
     * @private
     * @param params
     */
    render(params: any) {
        for (let viewIndex = 0; viewIndex < this.viewList.length; viewIndex++) {
            this.renderer.render(viewIndex, {force: true});
        }
    }

    #prefixMessageWithID(message: string): string {
        return ` [${this.constructor.name} "${inQuotes(this.id)}"]: ${message}`;
    }

    #registerView(view: View): void {
        if (this.views[view.id]) {
            return;
        }
        this.views[view.id] = view;
        for (let viewIndex = 0; ; viewIndex++) {
            if (!this.viewList[viewIndex]) {
                this.viewList[viewIndex] = view;
                this.numViews++;
                view.viewIndex = viewIndex;
                return;
            }
        }
    }

    #deregisterView(view: View): void {
        if (!this.views[view.id]) {
            return;
        }
        delete this.views[view.id];
        delete this.viewList[view.viewIndex];
        this.numViews--;
    }
}