import { ModelConverterResultOutput } from "./ModelConverterResultOutput";

/**
 * The result returned from a {@link ModelConverter.convert | ModelConverter.convert} operation.
 */
export interface ModelConverterResult {

    /**
     * The pipeline identifier used during the conversion.
     */
    pipeline: string;

    /**
     * The outputs generated by the conversion, keyed by output name as defined in the pipeline.
     */
    outputs: {
        [key: string]: ModelConverterResultOutput;
    };
}
