import {type ModelConverterResultInput} from "./ModelConverterResultInput";
import {type ModelConverterResultOutput} from "./ModelConverterResultOutput";
import {type Scene} from "../scene";
import {type Data} from "../data";
import {type ModelConverter} from "./ModelConverter";


/**
 * The result returned from a {@link ModelConverter.convert | ModelConverter.convert} operation.
 */
export interface ModelConverterResult {

  /**
   * The converter that created these results.
   */
  modelConverter: ModelConverter;


  scene: Scene;

  data: Data;

  /**
   * The pipeline identifier used during the conversion.
   */
  pipeline: string;

  /**
   * The inputs given to the conversion, keyed by input name as defined in the pipeline.
   */
  inputs: {
    [key: string]: ModelConverterResultInput;
  };

  /**
   * The outputs generated by the conversion, keyed by output name as defined in the pipeline.
   */
  outputs: {
    [key: string]: ModelConverterResultOutput;
  };
}
