import type { Data } from "../data";
import type { ModelConverterResultOutput } from "./ModelConverterResultOutput";
import type { Scene } from "../scene";

/**
 * The result returned from a {@link ModelConverter.convert | ModelConverter.convert} operation.
 */
export interface ModelConverterResult {

  scene: Scene;

  data: Data;

  /**
     * The pipeline identifier used during the conversion.
     */
  pipeline: string;

  /**
     * The outputs generated by the conversion, keyed by output name as defined in the pipeline.
     */
  outputs: {
    [key: string]: ModelConverterResultOutput;
  };
}
