/**
 * Provides info on the [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#DTX) generated by xeokit-convert.
 *
 * See {@link "@xeokit/DTX"} for usage.
 */
export const DTX_INFO = {

    /**
     * The [DTX](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#DTX) version generated by xeokit-convert.
     *
     * @property DTXVersion
     * @type {number}
     */
    DTXVersion: 11
};