/**
 * <img style="padding:20px" src="https://xeokit.github.io/sdk/docs/assets/geometry_icon.png"/>
 *
 * # xeokit Geometry Compression / Decompression Utilities
 *
 * This module provides geometry compression and decompression utilities used internally within
 * {@link scene!SceneModel.createGeometry | SceneModel.createGeometry}. These functions are exposed publicly,
 * allowing users to pre-compress geometry data before passing it to
 * {@link scene!SceneModel.createGeometryCompressed | SceneModel.createGeometryCompressed} for optimized rendering and storage.
 *
 * ## Compression Techniques
 *
 * The utilities in this module utilize the following compression techniques to reduce the size of 3D geometry data:
 *
 * * Merges duplicate vertex positions and updates indices to minimize data redundancy
 * * Generates edge indices for triangle meshes to facilitate faster rendering
 * * Omits normals (which are auto-generated by shaders during rendering)
 * * Converts positions to relative-to-center (RTC) coordinates for improved compression efficiency
 * * Quantizes positions and UVs as 16-bit unsigned integers for compact storage
 * * Compresses bounding box data and provides necessary matrices for efficient decompression
 *
 * ## Installation
 *
 * ```bash
 * npm install @xeokit/sdk
 * ```
 *
 * ## Usage
 *
 * The following examples demonstrate how to use the compression functions in this module:
 *
 * ### 1. Compressing Positions with AABB3 (Axis-Aligned Bounding Box)
 *
 * To compress a set of vertex positions, use the `compressPositions3` function, which quantizes the positions based on an AABB3:
 *
 * ```javascript
 * import {compressPositions3} from "@xeokit/sdk/compression";
 *
 * const positions = [0, 0, 0, 1, 1, 1, 2, 2, 2];
 * const aabb = [0, 0, 0, 2, 2, 2]; // The bounding box of the geometry
 *
 * const { quantized, decompressMatrix } = compressPositions3(positions, aabb);
 *
 * console.log(quantized); // The compressed (quantized) positions
 * console.log(decompressMatrix); // The matrix used for decompression
 * ```
 *
 * ### 2. Decompressing 3D Positions with a 4x4 Matrix
 *
 * To decompress a set of quantized positions using a transformation matrix, use the `decompressPositions3WithMat4` function:
 *
 * ```javascript
 * import {decompressPositions3WithMat4} from "@xeokit/sdk/compression";
 *
 * const quantizedPositions = [32767, 32767, 32767]; // Quantized data
 * const decompressMatrix = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]; // Example identity matrix
 *
 * const decompressedPositions = decompressPositions3WithMat4(quantizedPositions, decompressMatrix);
 *
 * console.log(decompressedPositions); // The decompressed positions
 * ```
 *
 * ### 3. Compressing UV Coordinates
 *
 * The `compressUVs` function compresses UV coordinates using a similar approach to position compression:
 *
 * ```javascript
 * import {compressUVs} from "@xeokit/sdk/compression";
 *
 * const uvs = [0.0, 0.0, 0.5, 0.5, 1.0, 1.0];
 * const minUV = [0.0, 0.0];
 * const maxUV = [1.0, 1.0];
 *
 * const { quantized, decompressMatrix } = compressUVs(uvs, minUV, maxUV);
 *
 * console.log(quantized); // The compressed (quantized) UVs
 * console.log(decompressMatrix); // The matrix for UV decompression
 * ```
 *
 * ### 4. Decompressing 3D Position with AABB3
 *
 * To decompress a point from quantized data back into real-world coordinates, you can use `decompressPoint3WithAABB3`:
 *
 * ```javascript
 * import {decompressPoint3WithAABB3} from "@xeokit/sdk/compression";
 *
 * const compressedPoint = [32767, 32767, 32767]; // Example quantized point
 * const aabb = [0, 0, 0, 1, 1, 1]; // The AABB3 used during compression
 *
 * const decompressedPoint = decompressPoint3WithAABB3(compressedPoint, aabb);
 *
 * console.log(decompressedPoint); // The real-world coordinates of the point
 * ```
 *
 * @module compression
 */
import type { FloatArrayParam } from "../math";
/**
 * Retrieves the minimum and maximum values for a set of 3D positions.
 *
 * This function calculates the minimum and maximum values along each axis (x, y, and z) from an array of 3D positions.
 * The array is assumed to be a flat array where every three consecutive values represent a 3D position (x, y, z).
 *
 * @param {FloatArrayParam} array - The array of 3D positions to evaluate. The array length must be a multiple of 3.
 * @param {FloatArrayParam} [min] - Optional pre-allocated array to store the minimum values. Defaults to a new array if not provided.
 * @param {FloatArrayParam} [max] - Optional pre-allocated array to store the maximum values. Defaults to a new array if not provided.
 * @returns {Object} - An object containing the min and max values as arrays:
 *  - `min`: The minimum values along the x, y, and z axes.
 *  - `max`: The maximum values along the x, y, and z axes.
 *
 * @example
 * const positions = new Float32Array([1, 2, 3, 4, 5, 6, -1, -2, -3]);
 * const { min, max } = getPositions3MinMax(positions);
 * console.log(min); // [-1, -2, -3]
 * console.log(max); // [4, 5, 6]
 */
export declare function getPositions3MinMax(array: FloatArrayParam, min?: FloatArrayParam, max?: FloatArrayParam): {
    min: FloatArrayParam;
    max: FloatArrayParam;
};
/**
 * Creates a 4x4 matrix for decompressing 3D positions based on a given axis-aligned bounding box (AABB).
 * This matrix is used to map compressed positions back to their original space.
 *
 * @param {FloatArrayParam} aabb - The axis-aligned bounding box (AABB) defined by [xmin, ymin, zmin, xmax, ymax, zmax].
 * @param {FloatArrayParam} [positionsDecompressMatrix] - An optional pre-allocated matrix to store the result. Defaults to a new matrix if not provided.
 * @returns {FloatArrayParam} - The decompression matrix used for transforming compressed positions back to their original scale.
 *
 * @example
 * const aabb = [0, 0, 0, 10, 10, 10];
 * const decompressionMatrix = createPositions3DecompressMat4(aabb);
 */
export declare function createPositions3DecompressMat4(aabb: FloatArrayParam, positionsDecompressMatrix?: FloatArrayParam): FloatArrayParam;
/**
 * Compresses a flat array of 3D positions into a quantized format, and computes the matrix for decompressing
 * back to the original range.
 *
 * @param {FloatArrayParam} array - The array of 3D positions to be compressed.
 * @param {FloatArrayParam} min - The minimum bounds for the 3D positions.
 * @param {FloatArrayParam} max - The maximum bounds for the 3D positions.
 * @returns {Object} - An object containing the quantized positions and the decompression matrix.
 *
 * @example
 * const positions = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6];
 * const min = [0, 0, 0];
 * const max = [1, 1, 1];
 * const { quantized, decompressMatrix } = compressPositions3(positions, min, max);
 */
export declare function compressPositions3(array: FloatArrayParam, min: FloatArrayParam, max: FloatArrayParam): {
    quantized: Uint16Array<ArrayBuffer>;
    decompressMatrix: FloatArrayParam;
};
/**
 * Compresses a single 3D point (p) within a specified axis-aligned bounding box (AABB) and stores the result in dest.
 * The point is quantized to fit within the range [0, 65535] based on the AABB bounds.
 *
 * @param {FloatArrayParam} p - The 3D point to be compressed.
 * @param {FloatArrayParam} aabb - The axis-aligned bounding box [xmin, ymin, zmin, xmax, ymax, zmax].
 * @param {FloatArrayParam} dest - The destination array where the compressed point will be stored. Defaults to the input point (p).
 * @returns {FloatArrayParam} - The compressed point in dest.
 *
 * @example
 * const point = [0.5, 0.5, 0.5];
 * const aabb = [0, 0, 0, 1, 1, 1];
 * const compressedPoint = compressPoint3WithAABB3(point, aabb);
 */
export declare function compressPoint3WithAABB3(p: FloatArrayParam, aabb: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses a 3D point (position) using a given 4x4 matrix (decompressMatrix).
 * This function applies the matrix transformations to the position to restore the original values.
 *
 * @param {FloatArrayParam} position - The compressed 3D point to be decompressed.
 * @param {FloatArrayParam} decompressMatrix - A 4x4 matrix used to decompress the position.
 * @param {FloatArrayParam} dest - The destination array to store the decompressed point. Defaults to the input position.
 * @returns {FloatArrayParam} - The decompressed 3D point stored in dest.
 *
 * @example
 * const compressedPosition = [100, 150, 200];
 * const matrix = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
 * const decompressedPoint = decompressPoint3WithMat4(compressedPosition, matrix);
 */
export declare function decompressPoint3WithMat4(position: FloatArrayParam, decompressMatrix: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses a 3D point (position) based on a given AABB (Axis-Aligned Bounding Box).
 * The function scales and offsets the position to restore it to its original coordinates.
 *
 * @param {FloatArrayParam} position - The compressed 3D point to be decompressed.
 * @param {FloatArrayParam} aabb - The AABB (min and max values) used to decompress the position.
 * @param {FloatArrayParam} dest - The destination array to store the decompressed point. Defaults to the input position.
 * @returns {FloatArrayParam} - The decompressed 3D point stored in dest.
 *
 * @example
 * const compressedPosition = [30000, 30000, 30000];
 * const aabb = [0, 0, 0, 10000, 10000, 10000];
 * const decompressedPoint = decompressPoint3WithAABB3(compressedPosition, aabb);
 */
export declare function decompressPoint3WithAABB3(position: FloatArrayParam, aabb: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses an AABB (Axis-Aligned Bounding Box) using a transformation matrix.
 * This function applies a matrix to each corner of the AABB to compute the decompressed AABB.
 *
 * @param {FloatArrayParam} aabb - The AABB values to be decompressed (min and max values).
 * @param {FloatArrayParam} decompressMatrix - The transformation matrix used to decompress the AABB.
 * @param {FloatArrayParam} dest - The destination array where the decompressed AABB will be stored. Defaults to the input AABB.
 * @returns {FloatArrayParam} - The decompressed AABB stored in `dest`.
 *
 * @example
 * const aabb = [0, 0, 0, 10, 10, 10]; // Example AABB
 * const matrix = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]; // Example identity matrix
 * const decompressedAABB = decompressAABB3WithMat4(aabb, matrix);
 */
export declare function decompressAABB3WithMat4(aabb: FloatArrayParam, decompressMatrix: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses an AABB (Axis-Aligned Bounding Box) using another AABB as reference for scaling and offset.
 * This function applies the scaling and offset defined by the second AABB to the first AABB.
 *
 * @param {FloatArrayParam} aabb - The AABB values to be decompressed (min and max values).
 * @param {FloatArrayParam} aabb2 - The reference AABB used for decompression (min and max values).
 * @param {FloatArrayParam} dest - The destination array where the decompressed AABB will be stored. Defaults to the input AABB.
 * @returns {FloatArrayParam} - The decompressed AABB stored in `dest`.
 *
 * @example
 * const aabb = [0, 0, 0, 10, 10, 10]; // Example AABB
 * const aabb2 = [0, 0, 0, 20, 20, 20]; // Example reference AABB for scaling
 * const decompressedAABB = decompressAABB3WithAABB3(aabb, aabb2);
 */
export declare function decompressAABB3WithAABB3(aabb: FloatArrayParam, aabb2: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses a flat array of quantized 3D positions using a 4x4 matrix for scaling and offsetting.
 *
 * This function applies the provided decompression matrix to the quantized positions. Each position is transformed by the matrix
 * to restore the original 3D coordinates. The decompression matrix should represent scaling and translation transformations.
 *
 * @param {FloatArrayParam} positions - The quantized positions array to be decompressed. Each position is a 3D point (x, y, z).
 * @param {FloatArrayParam} decompressMatrix - The 4x4 matrix used to decompress the positions. It contains scaling and translation values.
 * @param {Float32Array} [dest=new Float32Array(positions.length)] - The destination array to store the decompressed positions.
 * @returns {Float32Array} - The decompressed positions array.
 *
 * @example
 * const quantizedPositions = new Uint16Array([1000, 2000, 3000, 4000, 5000, 6000]);
 * const decompressMatrix = new Float32Array([
 *     1, 0, 0, 0,
 *     0, 1, 0, 0,
 *     0, 0, 1, 0,
 *     0, 0, 0, 1
 * ]);
 * const decompressed = decompressPositions3WithMat4(quantizedPositions, decompressMatrix);
 * console.log(decompressed); // [scaledX, scaledY, scaledZ, ...]
 */
export declare function decompressPositions3WithMat4(positions: FloatArrayParam, decompressMatrix: FloatArrayParam, dest?: Float32Array<any>): Float32Array<any>;
/**
 * Decompresses a flat array of quantized 3D positions using an axis-aligned bounding box (AABB) to scale and offset.
 *
 * This function restores the original 3D positions by scaling and offsetting the quantized values using the provided AABB.
 * It calculates the scale and offset for each axis based on the AABB and the maximum quantization value (65535).
 *
 * @param {FloatArrayParam} positions - The quantized positions array to be decompressed. Each position is a 3D point (x, y, z).
 * @param {FloatArrayParam} aabb - The AABB used for decompressing. The AABB contains 6 values: [xmin, ymin, zmin, xmax, ymax, zmax].
 * @param {FloatArrayParam} [dest=new Float32Array(positions.length)] - The destination array to store the decompressed positions.
 * @returns {FloatArrayParam} - The decompressed positions array.
 *
 * @example
 * const quantizedPositions = new Uint16Array([1000, 2000, 3000, 4000, 5000, 6000]);
 * const aabb = new Float32Array([0, 0, 0, 10000, 10000, 10000]);
 * const decompressed = decompressPositions3WithAABB3(quantizedPositions, aabb);
 * console.log(decompressed); // [0.015, 0.03, 0.045, 0.06, 0.075, 0.09]
 */
export declare function decompressPositions3WithAABB3(positions: FloatArrayParam, aabb: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Computes the minimum and maximum bounds for a flat array of UV coordinates.
 *
 * This function iterates over a flat array of UV coordinates and computes the
 * minimum and maximum values for each component (u, v). These bounds can be used
 * for various operations like normalization, quantization, or texture mapping.
 *
 * @param {FloatArrayParam} array - The input array of UV coordinates (each UV pair consisting of [u, v]).
 * @returns {Object} - An object containing:
 *   - `min`: The minimum values for each component ([u, v]).
 *   - `max`: The maximum values for each component ([u, v]).
 *
 * @example
 * const uvs = new Float32Array([0.1, 0.2, 0.5, 0.6, 0.3, 0.4]);
 * const { min, max } = getUVBounds(uvs);
 * console.log(min); // [0.1, 0.2]
 * console.log(max); // [0.5, 0.6]
 */
export declare function getUVBounds(array: FloatArrayParam): {
    min: FloatArrayParam;
    max: FloatArrayParam;
};
/**
 * Compresses a flat array of UV coordinates into a quantized representation.
 *
 * This function maps the input UV coordinates to a 16-bit integer range [0, 65535]
 * based on the provided min and max bounds for each coordinate. The resulting quantized
 * UVs are returned along with a matrix that can be used to decompress them back to
 * their original range. This is commonly used in texture mapping for more efficient storage.
 *
 * The compression uses a simple linear transformation based on the provided min and max values
 * for each component of the UV coordinates.
 *
 * @param {FloatArrayParam} array - The input array of UV coordinates (each UV pair consisting of [u, v]).
 * @param {FloatArrayParam} min - The minimum values for [u, v] coordinates to scale to the quantized range.
 * @param {FloatArrayParam} max - The maximum values for [u, v] coordinates to scale to the quantized range.
 * @returns {Object} - An object containing:
 *   - `quantized`: The quantized UV coordinates as a Uint16Array.
 *   - `decompressMatrix`: A matrix (either FloatArray or Float64Array) used to decompress the quantized UVs back to their original values.
 *
 * @example
 * const uvs = new Float32Array([0.1, 0.2, 0.5, 0.6]);
 * const min = new Float32Array([0, 0]);
 * const max = new Float32Array([1, 1]);
 * const { quantized, decompressMatrix } = compressUVs(uvs, min, max);
 */
export declare function compressUVs(array: FloatArrayParam, min: FloatArrayParam, max: FloatArrayParam): {
    quantized: Uint16Array<any>;
    decompressMatrix: FloatArrayParam;
};
/**
 * Oct-encodes a flat array of normal vectors
 * @param array
 */
/**
 * Compresses a flat array of 3D normal vectors using oct-encoding.
 *
 * This function compresses an array of 3D normal vectors into a smaller array of oct-encoded normals.
 * The compression minimizes storage requirements while preserving the direction of the normals.
 * The last element in each triplet is redundant due to a workaround for WebGL issues where
 * 2-element normals would not behave correctly in the shader.
 *
 * The function performs various oct-encoding operations using combinations of `ceil` and `floor` to
 * minimize rounding errors during compression.
 *
 * @param {FloatArrayParam} array - The input array of 3D normals (each consisting of three components: x, y, z).
 * @returns {Int8Array} The compressed array of oct-encoded normals, with redundant third components.
 *
 * @example
 * const normals = new Float32Array([1, 0, 0, 0, 1, 0, 0, 0, 1]);
 * const compressed = compressNormals(normals);
 * console.log(compressed); // Compressed oct-encoded normals
 */
export declare function compressNormals(array: FloatArrayParam): Int8Array<any>;
/**
 * Decompresses UV coordinates using a transformation matrix.
 *
 * This function applies a decompression matrix to a given UV coordinate,
 * adjusting it based on the transformation parameters.
 *
 * @param {FloatArrayParam} uv - The compressed UV coordinates as a 2-element array.
 * @param {FloatArrayParam} decompressMatrix - The 3x3 decompression matrix stored in a 1D array.
 * @param {FloatArrayParam} [dest] - Optional destination array for decompressed UVs. If not provided, a new Float32Array(2) is created.
 * @returns {FloatArrayParam} The decompressed UV coordinates.
 */
export declare function decompressUV(uv: FloatArrayParam, decompressMatrix: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses an array of UV coordinates using a transformation matrix.
 *
 * This function applies a decompression matrix to a batch of UV coordinates,
 * adjusting them based on the transformation parameters.
 *
 * @param {FloatArrayParam} uvs - The compressed UV coordinates (flat array).
 * @param {FloatArrayParam} decompressMatrix - The 3x3 decompression matrix stored in a 1D array.
 * @param {FloatArrayParam} [dest] - Optional destination array. If not provided, a new Float32Array is created.
 * @returns {FloatArrayParam} The decompressed UV coordinates.
 */
export declare function decompressUVs(uvs: FloatArrayParam, decompressMatrix: FloatArrayParam, dest?: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses a single oct-encoded normal vector into a 3D unit vector.
 *
 * @param {FloatArrayParam} oct - The compressed normal vector (2D).
 * @param {FloatArrayParam} result - The destination array to store the decompressed normal (3D).
 * @returns {FloatArrayParam} The decompressed 3D normal vector.
 */
export declare function decompressNormal(oct: FloatArrayParam, result: FloatArrayParam): FloatArrayParam;
/**
 * Decompresses an array of oct-encoded normal vectors into 3D unit vectors.
 *
 * @param {FloatArrayParam} octs - The compressed normal vectors (flat array).
 * @param {FloatArrayParam} result - The destination array to store the decompressed normals.
 * @returns {FloatArrayParam} The decompressed 3D normal vectors.
 */
export declare function decompressNormals(octs: FloatArrayParam, result: FloatArrayParam): FloatArrayParam;
/**
 * Quantizes 3D position data into a compressed 16-bit format and generates a matrix for decompressing the positions.
 * The function maps the 3D positions into a defined axis-aligned bounding box (AABB), scales them to fit into
 * a 16-bit integer range, and then constructs a transformation matrix (combining translation and scaling) for
 * future decompression operations.
 *
 * This process is commonly used in mesh compression to minimize the storage size of the positions while
 * maintaining the relative precision within the bounding box. The decompress matrix can be used to recover
 * the original positions after decompression.
 *
 * @param {FloatArrayParam} positions - A flat array of 3D position data (x, y, z).
 * @param {FloatArrayParam} aabb - The axis-aligned bounding box (AABB) represented as a 6-element array [xmin, ymin, zmin, xmax, ymax, zmax].
 * @param {FloatArrayParam} positionsDecompressMatrix - A 4x4 matrix to be populated with the transformation matrix for decompression.
 * @returns {Uint16Array} A new array containing the quantized positions in a compressed 16-bit format.
 *
 * @example
 * const positions = new Float32Array([0.5, 0.7, 1.0, 1.2, 1.8, 2.0]);
 * const aabb = new Float32Array([0, 0, 0, 2, 2, 2]);
 * const positionsDecompressMatrix = new Float32Array(16); // 4x4 matrix
 * const quantizedPositions = quantizePositions3AndCreateMat4(positions, aabb, positionsDecompressMatrix);
 * console.log(quantizedPositions);
 * console.log(positionsDecompressMatrix); // The transformation matrix for decompression
 */
export declare function quantizePositions3AndCreateMat4(positions: FloatArrayParam, aabb: FloatArrayParam, positionsDecompressMatrix: FloatArrayParam): Uint16Array<any>;
/**
 * Quantizes the position values of 3D coordinates into a compressed 16-bit representation.
 * The positions are mapped into a defined bounding box (AABB) and then scaled to fit into
 * a 16-bit integer range, minimizing precision loss.
 *
 * This process is commonly used in mesh compression techniques to reduce the _gpuMemoryManager footprint of
 * position data while maintaining relative accuracy within the bounds of the specified AABB.
 *
 * @param {FloatArrayParam} positions - A flat array of 3D position data (x, y, z).
 * @param {FloatArrayParam} aabb - The axis-aligned bounding box (AABB) represented as a 6-element array [xmin, ymin, zmin, xmax, ymax, zmax].
 * @returns {Uint16Array} A new array containing the quantized positions in a compressed 16-bit format.
 *
 * @example
 * const positions = new Float32Array([0.5, 0.7, 1.0, 1.2, 1.8, 2.0]);
 * const aabb = new Float32Array([0, 0, 0, 2, 2, 2]);
 * const quantizedPositions = quantizePositions3(positions, aabb);
 * console.log(quantizedPositions);
 */
export declare function quantizePositions3(positions: FloatArrayParam, aabb: FloatArrayParam): Uint16Array<any>;
/**
 * Transforms normals by applying a world normal matrix and then oct-encodes them to minimize rounding errors.
 *
 * This function takes an array of normals, transforms them using a world normal matrix, and then oct-encodes them
 * with optimizations to minimize rounding errors. The function tests different combinations of the `ceil` and `floor`
 * functions for the oct-encoding process and picks the encoding that maximizes the cosine similarity.
 *
 * @param {FloatArrayParam} worldNormalMatrix - A 4x4 matrix used to transform normals from local space to world space.
 * @param {FloatArrayParam} normals - A flat array of normals in local space (x, y, z components).
 * @param {number} lenNormals - The length of the `normals` array, indicating the number of normals to process.
 * @param {FloatArrayParam} compressedNormals - An array where the compressed normals will be stored.
 * @param {number} lenCompressedNormals - The length of the `compressedNormals` array before processing begins.
 * @returns {number} The updated length of the `compressedNormals` array.
 *
 * @example
 * const worldMatrix = new Float32Array([ ... 4x4 matrix ... ]);
 * const normals = new Float32Array([0.5, -0.5, 0.7, -0.3, 0.8, 0.5]);
 * const compressedNormals = new Float32Array(normals.length);
 * const newLen = transformAndOctEncodeNormals(worldMatrix, normals, normals.length, compressedNormals, 0);
 * console.log(newLen, compressedNormals);
 */
export declare function transformAndOctEncodeNormals(worldNormalMatrix: FloatArrayParam, normals: FloatArrayParam, lenNormals: number, compressedNormals: FloatArrayParam, lenCompressedNormals: number): number;
/**
 * Oct-encodes a 3D vector (x, y, z) into a 2-byte representation.
 *
 * This function normalizes a 3D vector to the 2D oct encoding range and encodes it
 * using the specified math functions (`xfunc` and `yfunc`), which typically are 'floor' or 'ceil'.
 *
 * @param {FloatArrayParam} p - A 3D vector, typically representing a normal (x, y, z).
 * @param {string} xfunc - The math function to apply to the x component ('floor', 'ceil', etc.).
 * @param {string} yfunc - The math function to apply to the y component ('floor', 'ceil', etc.).
 * @returns {Int8Array} The oct-encoded 2D vector as a 2-element Int8Array.
 *
 * @throws {Error} If xfunc or yfunc are not valid function names.
 *
 * @example
 * const vec3 = new Float32Array([0.5, -0.5, 0.5]);
 * const encoded = octEncodeVec3(vec3, 'floor', 'ceil');
 * console.log(encoded); // Int8Array with encoded vector values
 */
export declare function octEncodeVec3(p: FloatArrayParam, xfunc: string, yfunc: string): Int8Array<any>;
/**
 * Oct-encodes a single normal vector (x, y) into a 2-byte representation.
 *
 * This function normalizes the 3D normal vector to the 2D oct encoding range and encodes it
 * using a specified math function (`xfunc` and `yfunc` are typically 'floor' or 'ceil').
 *
 * @param {FloatArrayParam} array - The array containing the 3D normal vector.
 * @param {number} i - The index of the normal vector's x component in the array.
 * @param {string} xfunc - The math function to apply to the x component ('floor', 'ceil', etc.).
 * @param {string} yfunc - The math function to apply to the y component ('floor', 'ceil', etc.).
 * @returns {Int8Array} The oct-encoded normal vector as a 2-element Int8Array.
 *
 * @throws {Error} If xfunc or yfunc are not valid function names.
 *
 * @example
 * const normal = new Float32Array([0.5, -0.5, 0.5]);
 * const encoded = octEncodeNormal(normal, 0, 'floor', 'ceil');
 * console.log(encoded); // Int8Array with encoded normal values
 */
export declare function octEncodeNormal(array: FloatArrayParam, i: number, xfunc: string, yfunc: string): Int8Array<any>;
/**
 * Compresses a flat array of floating-point RGB or RGBA colors into a Uint16Array.
 *
 * This function scales floating-point color values (0.0 to 1.0) to an 8-bit range (0-255),
 * storing them in a `Uint16Array` for reduced _gpuMemoryManager usage.
 *
 * @param {FloatArrayParam} colors - A flat array of floating-point color values (RGB or RGBA).
 *                                   Each color component should be in the range [0, 1].
 * @returns {Uint16Array} A compressed Uint16Array where each value represents a color channel (0-255).
 *
 * @throws {Error} If input contains values outside the expected [0,1] range.
 *
 * @example
 * const colors = new Float32Array([0.5, 0.2, 0.8, 1.0, 0.3, 0.6, 0.1, 1.0]);
 * const compressed = compressRGBColors(colors);
 * console.log(compressed); // Uint16Array([127, 51, 204, 255, 76, 153, 25, 255])
 */
export declare function compressRGBColors(colors: FloatArrayParam): Uint16Array<any>;
//# sourceMappingURL=index.d.ts.map
