/**
 * Provides info on the [XGF](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xgf) generated by {@link @xeokit/xgf!saveXGF | saveXGF}.
 *
 * See {@link "@xeokit/xgf" | @xeokit/xgf} for usage.
 */
export const XGF_INFO = {

    /**
     * The [XGF](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xgf) version generated by {@link @xeokit/xgf!saveXGF | saveXGF}.
     *
     * @property xgfVersion
     * @type {number}
     */
    xgfVersion: 1
};
