import {identityMat4} from "../../../../base/math/matrix";

export const GPU_BUFFER_USAGE = {
  MAP_READ: 1,
  COPY_SRC: 4,
  COPY_DST: 8,
  INDIRECT: 256,
  INDEX: 16,
  QUERY_RESOLVE: 512,
  STORAGE: 128,
  VERTEX: 32,
  UNIFORM: 64
} as const;

export const GPU_TEXTURE_USAGE = {
  COPY_SRC: 1,
  COPY_DST: 2,
  TEXTURE_BINDING: 4,
  RENDER_ATTACHMENT: 16
} as const;

export const GPU_SHADER_STAGE = {
  VERTEX: 1,
  FRAGMENT: 2
} as const;

export const DEPTH_FORMAT = "depth24plus-stencil8";
export const SHADOW_DEPTH_FORMAT = "depth32float";
export const ID_BUFFER_FORMAT = "rgba8unorm";
export const MAX_DIR_LIGHTS = 3;
export const MAX_SECTION_PLANES = 8;
export const AMBIENT_LIGHT_UNIFORM_OFFSET = 16;
export const DIR_LIGHT_DIRECTION_UNIFORM_OFFSET = AMBIENT_LIGHT_UNIFORM_OFFSET + 4;
export const DIR_LIGHT_COLOR_UNIFORM_OFFSET = DIR_LIGHT_DIRECTION_UNIFORM_OFFSET + MAX_DIR_LIGHTS * 4;
export const SECTION_PLANE_STATE_UNIFORM_OFFSET = DIR_LIGHT_COLOR_UNIFORM_OFFSET + MAX_DIR_LIGHTS * 4;
export const SECTION_PLANE_UNIFORM_OFFSET = SECTION_PLANE_STATE_UNIFORM_OFFSET + 4;
export const SECTION_PLANE_CAP_COLOR_UNIFORM_OFFSET = SECTION_PLANE_UNIFORM_OFFSET + MAX_SECTION_PLANES * 4;
export const DEPTH_PARAMS_UNIFORM_OFFSET = SECTION_PLANE_CAP_COLOR_UNIFORM_OFFSET + MAX_SECTION_PLANES * 4;
export const POINT_PARAMS_UNIFORM_OFFSET = DEPTH_PARAMS_UNIFORM_OFFSET + 4;
export const LINE_PARAMS_UNIFORM_OFFSET = POINT_PARAMS_UNIFORM_OFFSET + 8;
export const VIEW_MATRIX_UNIFORM_OFFSET = LINE_PARAMS_UNIFORM_OFFSET + 4;
export const SPLAT_PARAMS_UNIFORM_OFFSET = VIEW_MATRIX_UNIFORM_OFFSET + 16;
export const HEMISPHERE_SKY_UNIFORM_OFFSET = SPLAT_PARAMS_UNIFORM_OFFSET + 4;
export const HEMISPHERE_GROUND_UNIFORM_OFFSET = HEMISPHERE_SKY_UNIFORM_OFFSET + 4;
export const HEMISPHERE_UP_UNIFORM_OFFSET = HEMISPHERE_GROUND_UNIFORM_OFFSET + 4;
export const EDGE_PARAMS_UNIFORM_OFFSET = HEMISPHERE_UP_UNIFORM_OFFSET + 4;
export const EDGE_COLOR_UNIFORM_OFFSET = EDGE_PARAMS_UNIFORM_OFFSET + 4;
export const FRAME_UNIFORM_FLOATS = EDGE_COLOR_UNIFORM_OFFSET + 4;
export const FRAME_UNIFORM_BYTES = FRAME_UNIFORM_FLOATS * 4;
export const RTC_TILE_FLOATS = 20;
export const RTC_TILE_BYTES = RTC_TILE_FLOATS * 4;
export const INSTANCE_FLOATS = 36;
export const INSTANCE_BYTES = INSTANCE_FLOATS * 4;
export const MAX_SHADOW_CASCADES = 6;
export const SHADOW_UNIFORM_FLOATS = 152;
export const SHADOW_UNIFORM_BYTES = SHADOW_UNIFORM_FLOATS * 4;
export const IDENTITY_MATRIX = identityMat4();
export const WEBGPU_CLIP_SPACE_MATRIX = [
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 0.5, 0,
  0, 0, 0.5, 1
];
