import {type ModelConverterResultInput} from "./ModelConverterResultInput";
import {type ModelConverterResultOutput} from "./ModelConverterResultOutput";
import {type ModelConverterResultInspection} from "./ModelConverterResultInspection";
import {type Scene} from "../../model/scene";
import {type Data} from "../../model/data";
import {type ModelConverter} from "./ModelConverter";


/**
 * The result returned from a {@link ModelConverter.convert | ModelConverter.convert} operation.
 */
export interface ModelConverterResult {

  /**
   * The converter that created these results.
   */
  modelConverter: ModelConverter;

  /**
   * The scene model produced by the conversion.
   */
  scene: Scene;

  /**
   * The data model produced by the conversion.
   */
  data: Data;

  /**
   * The pipeline identifier used during the conversion.
   */
  pipeline: string;

  /**
   * The inputs given to the conversion, keyed by input name as defined in the pipeline.
   */
  inputs: {
    [key: string]: ModelConverterResultInput;
  };

  /**
   * The outputs generated by the conversion, keyed by output name as defined in the pipeline.
   */
  outputs: {
    [key: string]: ModelConverterResultOutput;
  };

  /**
   * Inspection results, present when the pipeline had an
   * {@link ModelConverterPipelineConfig.inspect | inspect} block
   * enabled. Keyed by SceneModel id — a SceneModel fed by multiple
   * inputs is inspected once after `processInputs` completes.
   *
   * If `inspect.failOnErrors` triggered, `outputs` is empty and the
   * matching SceneModel entry's `report.errors` carries the reason.
   */
  inspection?: {
    bySceneModel: {
      [sceneModelId: string]: ModelConverterResultInspection;
    };
  };

  /**
   * Any errors that occurred during the conversion.
   */
  errors: string[];
}
