/**
 * Caches reusable resources for {@link rayPick} and {@link marqueePick}.
 *
 * These resources are lazy-generated by these methods. When provided
 * again to the methods, we can avoid the method needing to re-generate them.
 *
 * > Internally, the resources consist of lazy-generated {@link PrimsKdTree3 | PrimsKdTree3s}, cached for
 * {@link @xeokit/scene!SceneGeometryBucket | GeometryBuckets} of
 * candidate {@link @xeokit/scene!SceneObject | SceneObjects} while picking.
 */
export class PickPrimsCache {
    /**
     * TODO
     */
    primitivesKdTrees;
    /**
     * TODO
     */
    constructor() {
        this.primitivesKdTrees = {};
    }
    /**
     * TODO
     */
    clear() {
        this.primitivesKdTrees = {};
    }
}
//# sourceMappingURL=PickPrimsCache.js.map