#!/usr/bin/env node

const yargs = require("yargs/yargs");
const {hideBin} = require("yargs/helpers");
const {reporters, modelConverter} = require("./xeoconvert_core.cjs.js");
const npmPackage = require('./../../package.json');
const fs = require('fs');
const path = require("path");

const argv = yargs(hideBin(process.argv)).argv;

const logEnabled = argv.log;

function logInfo(msg) {
  if (logEnabled) {
    console.log(`[xeoconvert] ${msg}`);
  }
}

function logError(msg) {
  console.error(`[xeoconvert] ${msg}`);
}

try {

  if (argv.help) {
    console.log(`xeoconvert - Model Conversion CLI Tool

Usage:
  node xeoconvert.js --pipeline <pipelineName> --<inputId> <inputFile> --<outputId> <outputFile> [options]

Required:
  --pipeline <name>           Name of the conversion pipeline to run. Available pipelines are: ${Object.keys(modelConverter.pipelines).join(", ")}
  --<inputId> <inputFile>     Input file(s) required by the pipeline
  --<outputId> <outputFile>   Output file(s) generated by the pipeline

Options:
  --log                       Enable verbose logging
  --<reporterId> <reportFile> Generate a conversion report. Available reporters are: ${Object.keys(reporters).join(", ")}
  --help                      Show this help message

Inspection (run sceneModelInspector on each loaded SceneModel before export):
  --inspect                   Enable inspection. Implied by any other --inspect-* flag.
  --inspect-fix               Run applyFixes after inspection (skipped if errors present).
  --inspect-checks <list>     Comma-separated opt-in checks. Available:
                                dup, similar, dense, large, quality, objects, textures, geom-far, all
  --no-fail-on-inspect-errors Continue to export even when inspection found errors. Default is to abort.
  --inspect-async             Use inspectSceneModelAsync (non-blocking, useful for very large models).
  --inspection-report <file>  Write a JSON inspection report (this is also a reporter — listed above).

Example:
  node xeoconvert.js --pipeline ifc2xgf --ifc model.ifc --xgf sceneModel.xgf --datamodel dataModel.json --stats-report manifest.json --log

Example (inspect + auto-fix + write report):
  node xeoconvert.js --pipeline ifc2xgf --ifc model.ifc --xgf sceneModel.xgf --datamodel dataModel.json \\
    --inspect-fix --inspect-checks all --inspection-report inspection.json --log
`);
    process.exit(0);
  }

  if (!argv.pipeline) {
    console.error("Error: Missing required argument --pipeline");
    process.exit(-1);
  }

  const pipeline = modelConverter.pipelines[argv.pipeline];
  if (!pipeline) {
    logError(`Error: Unknown pipeline '${argv.pipeline}'. Available options: ${Object.keys(modelConverter.pipelines).join(", ")}`);
    process.exit(-1);
    return;
  }

  for (let inputId in pipeline.inputs) {
    if (!argv[inputId]) {
      logError(`Error: Missing input argument --${inputId}, required for --pipeline ${argv.pipeline}`);
      process.exit(-1);
    }
  }

  for (let outputId in pipeline.outputs) {
    if (!argv[outputId]) {
      logError(`Error: Missing output argument --${outputId}, required for --pipeline ${argv.pipeline}`);
      process.exit(-1);
    }
  }

  // Synthesize an `inspect` block on the pipeline from CLI flags.
  // Any --inspect-* flag implies --inspect.
  const inspectFlagsPresent =
    argv.inspect ||
    argv["inspect-fix"] ||
    argv["inspect-checks"] !== undefined ||
    argv["inspect-async"];
  if (inspectFlagsPresent) {
    const checksMap = {
      "dup":      "checkDuplicateGeometries",
      "similar":  "checkSimilarGeometries",
      "dense":    "checkDenseGeometries",
      "large":    "checkLargeGeometries",
      "quality":  "checkGeometryQuality",
      "objects":  "checkObjectStructure",
      "textures": "checkTextureSanity",
      "geom-far": "checkGeometryFarFromOrigin",
    };
    const checks = {};
    const raw = argv["inspect-checks"];
    if (raw !== undefined) {
      const tokens = String(raw).split(",").map(s => s.trim()).filter(Boolean);
      const expand = tokens.includes("all") ? Object.keys(checksMap) : tokens;
      for (const t of expand) {
        const k = checksMap[t];
        if (!k) {
          logError(`Error: Unknown --inspect-checks token '${t}'. Available: ${Object.keys(checksMap).concat(["all"]).join(", ")}`);
          process.exit(-1);
        }
        checks[k] = true;
      }
    }
    pipeline.inspect = {
      enabled:      true,
      checks,
      fix:          !!argv["inspect-fix"],
      // yargs maps --no-fail-on-inspect-errors to argv["fail-on-inspect-errors"] === false.
      failOnErrors: argv["fail-on-inspect-errors"] !== false,
      async:        !!argv["inspect-async"],
    };
    logInfo(`Inspection enabled (checks: ${Object.keys(checks).length ? Object.keys(checks).join(",") : "default"}, fix: ${pipeline.inspect.fix}, failOnErrors: ${pipeline.inspect.failOnErrors})`);
  }

  logInfo(`Running conversion pipeline '${argv.pipeline}'`);

  const conversionParams = {
    pipeline: argv.pipeline,
    inputs: {}
  };

  logInfo(`Reading inputs`);

  for (let inputId in pipeline.inputs) {

    const pipelineInput = pipeline.inputs[inputId];
    const modelLoader = modelConverter.loaders[pipelineInput.loader];
    const inputFilePath = argv[inputId];

    let fileData;
    let fileDataSizeBytes;

    logInfo(`Reading input --${inputId} ${inputFilePath}`);

    switch (modelLoader.fileDataType) {
      case "text":
        fileData = fs.readFileSync(inputFilePath, "utf-8");
        fileDataSizeBytes = (new TextEncoder()).encode(fileData).length;
        break;
      case "json":
        const text = fs.readFileSync(inputFilePath, "utf-8");
        fileData = JSON.parse(text);
        fileDataSizeBytes = (new TextEncoder()).encode(text).length;
        break;
      default:
        fileData = fs.readFileSync(inputFilePath);
        fileDataSizeBytes = fileData.buffer.byteLength;
        break;
    }

    conversionParams.inputs[inputId] = {fileData};
  }

  logInfo(`Converting`);

  modelConverter
    .convert(conversionParams)
    .then(modelConverterResult => {

      logInfo(`Conversion complete`);
      logInfo(`Writing outputs`);

      for (let inputId in pipeline.inputs) {
        const inputValue = modelConverterResult.inputs[inputId];
        if (inputValue) {
          const inputFilePath = argv[inputId];
          inputValue.filePath = inputFilePath;
        }
      }

      for (let outputId in modelConverterResult.outputs) {

        const outputFilePath = argv[outputId];
        if (!outputFilePath) {
          continue;
        }

        const dirName = path.dirname(outputFilePath);
        if (dirName !== "" && !fs.existsSync(dirName)) {
          fs.mkdirSync(dirName, {recursive: true});
        }

        logInfo(`Writing output --${outputId} ${outputFilePath}`);

        const outputValue = modelConverterResult.outputs[outputId];

        switch (outputValue.fileDataType) {
          case "json":
            fs.writeFileSync(outputFilePath, JSON.stringify(outputValue.fileData));
            break;
          case "text":
            fs.writeFileSync(outputFilePath, outputValue.fileData);
            break;
          default:
            fs.writeFileSync(outputFilePath, Buffer.from(outputValue.fileData));
            break;
        }

        outputValue.filePath = outputFilePath;
      }

      for (let reporterId in reporters) {
        const reportPath = argv[reporterId];
        if (reportPath === undefined) {
          continue;
        }
        if (reportPath === true || reportPath === "") {
          logError(`Error: --${reporterId} requires a file path.`);
          process.exit(-1);
        }
        const reporter = reporters[reporterId];
        const report = reporter(modelConverterResult);
        if (report === null) {
          logInfo(`Reporter '${reporterId}' produced no output (skipped).`);
          continue;
        }
        if (!report) {
          logError(`Error: Reporter '${reporterId}' failed to generate report.`);
          process.exit(-1);
        }
        const dirName = path.dirname(reportPath);
        if (dirName !== "" && !fs.existsSync(dirName)) {
          fs.mkdirSync(dirName, {recursive: true});
        }
        logInfo(`Reporter '${reporterId}' writing report to ${reportPath}`);
        fs.writeFileSync(reportPath, JSON.stringify(report, null, 4));
      }
      logInfo(`Done.`);
      process.exit(1);
    });
} catch (err) {
  logError(err);
  process.exit(-1);
}

