/**
 * Provides info on the [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) generated by {@link @xeokit/xkt!saveXKT}.
 *
 * See {@link "@xeokit/xkt" | @xeokit/xkt} for usage.
 */
export const XKT_INFO = {

    /**
     * The [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) version generated by {@link @xeokit/xkt!saveXKT}.
     *
     * @property xktVersion
     * @type {number}
     */
    xktVersion: 10
};
