import {KdTree3D, PrimsKdTree3D, SceneObjectsPrimsKdTree3D} from "../kdtree3d";
import {FloatArrayParam} from "@xeokit/math/math";

/**
 * Caches reusable resources for {@link rayPick} and {@link marqueePick}.
 *
 * These resources are lazy-generated by these methods. When provided
 * again to the methods, we can avoid the method needing to re-generate them.
 *
 * > Internally, the resources consist of lazy-generated {@link PrimsKdTree3D | PrimsKdTree3Ds}, cached for
 * {@link @xeokit/scene!GeometryBucket | GeometryBuckets} of
 * candidate {@link @xeokit/scene!SceneObject | SceneObjects} while picking.
 */
export class PickPrimsCache {

    /**
     * TODO
     */
    primitivesKdTrees: {
        [key: string]: {
            primitivesKdTree: PrimsKdTree3D,
            positions: FloatArrayParam
        }
    };

    /**
     * TODO
     */
    constructor() {
        this.primitivesKdTrees = {};
    }

    /**
     * TODO
     */
    clear() {
        this.primitivesKdTrees = {};
    }
}