import { WebGLAttribute, WebGLProgram } from "../../webglutils";
import { RenderContext } from "../RenderContext";
import { VBOInstancingLayer } from "./instancing/VBOInstancingLayer";
import { VBOBatchingLayer } from "./batching/VBOBatchingLayer";
/**
 * @private
 */
export declare abstract class VBORenderer {
    #private;
    renderContext: RenderContext;
    hash: string;
    program: WebGLProgram | null;
    errors: string[];
    edges: boolean;
    uniforms: {
        pointCloudIntensityRange: WebGLUniformLocation;
        nearPlaneHeight: WebGLUniformLocation;
        silhouetteColor: WebGLUniformLocation;
        gammaFactor: WebGLUniformLocation;
        pickZNear: WebGLUniformLocation;
        renderPass: WebGLUniformLocation;
        snapCameraEyeRTC: WebGLUniformLocation;
        pointSize: WebGLUniformLocation;
        intensityRange: WebGLUniformLocation;
        pickZFar: WebGLUniformLocation;
        pickClipPos: WebGLUniformLocation;
        drawingBufferSize: WebGLUniformLocation;
        worldMatrix: WebGLUniformLocation;
        positionsDecompressOffset: WebGLUniformLocation;
        positionsDecompressScale: WebGLUniformLocation;
        sectionPlanes: any[];
        sceneModelMatrix: WebGLUniformLocation;
        projMatrix: WebGLUniformLocation;
        viewMatrix: WebGLUniformLocation;
        lightPos: WebGLUniformLocation[];
        lightDir: WebGLUniformLocation[];
        lightColor: WebGLUniformLocation[];
        lightAttenuation: WebGLUniformLocation[];
        lightAmbient: WebGLUniformLocation;
        saoParams: WebGLUniformLocation;
    };
    attributes: {
        color: WebGLAttribute;
        normal: WebGLAttribute;
        intensity: WebGLAttribute;
        flags: WebGLAttribute;
        uv: WebGLAttribute;
        position: WebGLAttribute;
        pickColor: WebGLAttribute;
        modelMatrix: WebGLAttribute;
        modelMatrixCol0: WebGLAttribute;
        modelMatrixCol1: WebGLAttribute;
        modelMatrixCol2: WebGLAttribute;
    };
    samplers: {
        saoOcclusionTexture: "saoOcclusionTexture";
    };
    constructor(renderContext: RenderContext, cfg?: {
        edges: boolean;
    });
    abstract getHash(): string;
    get lambertShadingHash(): string;
    get slicingHash(): string;
    get pointsHash(): string;
    needRebuild(): void;
    getValid(): boolean;
    build(): void;
    abstract buildVertexShader(src: string[]): any;
    abstract buildFragmentShader(src: string[]): any;
    vertexHeader(src: string[]): void;
    vertexCommonDefs(src: string[]): void;
    vertexBatchingTransformDefs(src: string[]): void;
    vertexInstancingTransformDefs(src: string[]): void;
    vertexPickMeshDefs(src: string[]): void;
    vertexSlicingDefs(src: string[]): void;
    vertexDrawMainOpen(src: string[]): void;
    vertexSilhouetteMainOpen(src: string[]): void;
    vertexPickMainOpen(src: string[]): void;
    vertexMainClose(src: string[]): void;
    vertexSlicingLogic(src: string[]): void;
    vertexDrawBatchingTransformLogic(src: string[]): void;
    vertexDrawPointsBatchingTransformLogic(src: string[]): void;
    vertexPickBatchingTransformLogic(src: string[]): void;
    vertexDrawInstancingTransformLogic(src: string[]): void;
    vertexPickInstancingTransformLogic(src: string[]): void;
    vertexDrawLambertDefs(src: string[]): void;
    vertexDrawLambertLogic(src: string[]): void;
    vertexSilhouetteDefs(src: string[]): void;
    vertexSilhouetteLogic(src: string[]): void;
    vertexDrawFlatColorLogic(src: string[]): void;
    vertexDrawFlatColorDefs(src: string[]): void;
    vertexDrawEdgesColorLogic(src: string[]): void;
    vertexPickMeshLogic(src: string[]): void;
    vertexPointsDrawDefs(src: string[]): void;
    vertexDrawPointsColorsLogic(src: string[]): void;
    vertexPointsGeometryDefs(src: string[]): void;
    vertexPointsFilterLogicOpenBlock(src: string[]): void;
    vertexPointsFilterLogicCloseBlock(src: string[]): void;
    vertexPointsGeometryLogic(src: string[]): void;
    fragmentHeader(src: string[]): void;
    fragmentPrecisionDefs(src: string[]): void;
    fragmentCommonDefs(src: string[]): void;
    fragmentDrawLambertDefs(src: string[]): void;
    fragmentDrawLambertLogic(src: string[]): void;
    fragmentDrawSAODefs(src: string[]): void;
    fragmentSilhouetteDefs(src: string[]): void;
    fragmentDrawFlatColorDefs(src: string[]): void;
    fragmentDrawFlatColorLogic(src: string[]): void;
    fragmentDrawSAOLogic(src: string[]): void;
    fragmentDrawDepthDefs(src: string[]): void;
    fragmentDrawDepthLogic(src: string[]): void;
    fragmentSilhouetteLogic(src: string[]): void;
    fragmentPickMeshDefs(src: string[]): void;
    fragmentPickMeshLogic(src: string[]): void;
    fragmentSlicingDefs(src: string[]): void;
    fragmentSlicingLogic(src: string[]): void;
    fragmentPointsGeometryLogic(src: string[]): void;
    fragmentCommonOutput(src: string[]): void;
    bind(renderPass: number): boolean;
    renderVBOInstancingLayer(vboInstancinglayer: VBOInstancingLayer, renderPass: number): void;
    renderVBOBatchingLayer(vboInstancinglayer: VBOBatchingLayer, renderPass: number): void;
    destroy(): void;
}
//# sourceMappingURL=LayerRenderer.d.ts.map
