import {
  applyFixesResultToJson,
  inspectionReportToJson,
} from "../../../../quality/sceneModel";
import {inspectionReportToJson as dataInspectionReportToJson} from "../../../../quality/dataModel";
import {type ModelConverterReporter} from "../ModelConverterReporter";
import {type ModelConverterResult} from "../../ModelConverterResult";
import {
  type ModelConverterInspectionReport,
  type ModelConverterInspectionReportEntry,
  type ModelConverterDataInspectionReportEntry,
  type ModelConverterReportFile,
} from "./ModelConverterInspectionReport";

/**
 * Generate a JSON-ready report of every per-SceneModel inspection
 * result attached to a {@link ModelConverterResult}. Returns
 * `null` when the conversion didn't run inspection (no `inspect`
 * block on the pipeline) — the CLI's reporter dispatcher treats
 * `null` as "nothing to write".
 *
 * Per-SceneModel `InspectionReport` / `ApplyFixesResult` objects
 * are converted with {@link inspectionReportToJson} /
 * {@link applyFixesResultToJson} so the final blob is
 * `JSON.stringify`-safe (no `Map` / class instances).
 */
export const createInspectionReport: ModelConverterReporter = (
  pipelineResult: ModelConverterResult,
): ModelConverterInspectionReport | null => {

  const inspection = pipelineResult.inspection;
  if (!inspection) return null;

  const counts = {
    sceneModels: 0,
    dataModels:  0,
    errors:      0,
    warnings:    0,
    info:        0,
    fixed:       0,
    skipped:     0,
    fixErrors:   0,
  };

  const bySceneModel: { [id: string]: ModelConverterInspectionReportEntry } = {};

  for (const id of Object.keys(inspection.bySceneModel)) {
    const entry = inspection.bySceneModel[id];
    counts.sceneModels++;
    counts.errors   += entry.report.errors.length;
    counts.warnings += entry.report.warnings.length;
    counts.info     += entry.report.info.length;
    if (entry.fixResult) {
      counts.fixed     += entry.fixResult.fixed.length;
      counts.skipped   += entry.fixResult.skipped.length;
      counts.fixErrors += entry.fixResult.errors.length;
    }
    bySceneModel[id] = {
      sceneModel: entry.sceneModel,
      report:     inspectionReportToJson(entry.report),
      fixResult:  entry.fixResult ? applyFixesResultToJson(entry.fixResult) : undefined,
      reReport:   entry.reReport  ? inspectionReportToJson(entry.reReport) : undefined,
      durationMs: entry.durationMs,
    };
  }

  let byDataModel: { [id: string]: ModelConverterDataInspectionReportEntry } | undefined;
  if (inspection.byDataModel) {
    byDataModel = {};
    for (const id of Object.keys(inspection.byDataModel)) {
      const entry = inspection.byDataModel[id];
      counts.dataModels++;
      counts.errors   += entry.report.errors.length;
      counts.warnings += entry.report.warnings.length;
      counts.info     += entry.report.info.length;
      byDataModel[id] = {
        dataModel:  entry.dataModel,
        report:     dataInspectionReportToJson(entry.report),
        durationMs: entry.durationMs,
      };
    }
  }

  return {
    description: "Generated by @xeokit/sdk/conversion/pipeline/createInspectionReport",
    generatedAt: new Date().toISOString(),
    pipeline:    pipelineResult.pipeline,
    counts,
    bySceneModel,
    byDataModel,
    files:       collectFileSizes(pipelineResult),
  };
};

/**
 * Input/output file sizes, read straight off the converter result — the
 * {@link ModelConverter} already recorded `fileDataSizeBytes` at the I/O
 * boundary, so the reporter just projects it (no filesystem access here).
 */
function collectFileSizes(
  result: ModelConverterResult,
): ModelConverterInspectionReport["files"] {
  const project = (
    group: { [id: string]: { filePath?: string; fileFormat: string; fileDataSizeBytes: number } },
  ): { files: { [id: string]: ModelConverterReportFile }; total: number } => {
    const files: { [id: string]: ModelConverterReportFile } = {};
    let total = 0;
    for (const id of Object.keys(group)) {
      const e = group[id];
      files[id] = {filePath: e.filePath, fileFormat: e.fileFormat, fileDataSizeBytes: e.fileDataSizeBytes};
      total += e.fileDataSizeBytes || 0;
    }
    return {files, total};
  };
  const inputs  = project(result.inputs);
  const outputs = project(result.outputs);
  return {
    inputs:           inputs.files,
    outputs:          outputs.files,
    totalInputBytes:  inputs.total,
    totalOutputBytes: outputs.total,
  };
}
