import {
  applyFixesResultToJson,
  inspectionReportToJson,
} from "../../../sceneModelInspector";
import {type ModelConverterReporter} from "../ModelConverterReporter";
import {type ModelConverterResult} from "../../ModelConverterResult";
import {
  type ModelConverterInspectionReport,
  type ModelConverterInspectionReportEntry,
} from "./ModelConverterInspectionReport";

/**
 * Generate a JSON-ready report of every per-SceneModel inspection
 * result attached to a {@link ModelConverterResult}. Returns
 * `null` when the conversion didn't run inspection (no `inspect`
 * block on the pipeline) — the CLI's reporter dispatcher treats
 * `null` as "nothing to write".
 *
 * Per-SceneModel `InspectionReport` / `ApplyFixesResult` objects
 * are converted with {@link inspectionReportToJson} /
 * {@link applyFixesResultToJson} so the final blob is
 * `JSON.stringify`-safe (no `Map` / class instances).
 */
export const createInspectionReport: ModelConverterReporter = (
  modelConverterResult: ModelConverterResult,
): ModelConverterInspectionReport | null => {

  const inspection = modelConverterResult.inspection;
  if (!inspection) return null;

  const counts = {
    sceneModels: 0,
    errors:      0,
    warnings:    0,
    info:        0,
    fixed:       0,
    skipped:     0,
    fixErrors:   0,
  };

  const bySceneModel: { [id: string]: ModelConverterInspectionReportEntry } = {};

  for (const id of Object.keys(inspection.bySceneModel)) {
    const entry = inspection.bySceneModel[id];
    counts.sceneModels++;
    counts.errors   += entry.report.errors.length;
    counts.warnings += entry.report.warnings.length;
    counts.info     += entry.report.info.length;
    if (entry.fixResult) {
      counts.fixed     += entry.fixResult.fixed.length;
      counts.skipped   += entry.fixResult.skipped.length;
      counts.fixErrors += entry.fixResult.errors.length;
    }
    bySceneModel[id] = {
      sceneModel: entry.sceneModel,
      report:     inspectionReportToJson(entry.report),
      fixResult:  entry.fixResult ? applyFixesResultToJson(entry.fixResult) : undefined,
      reReport:   entry.reReport  ? inspectionReportToJson(entry.reReport) : undefined,
      durationMs: entry.durationMs,
    };
  }

  return {
    description: "Generated by @xeokit/sdk/modelConverter/createInspectionReport",
    generatedAt: new Date().toISOString(),
    pipeline:    modelConverterResult.pipeline,
    counts,
    bySceneModel,
  };
};
