/**
 * Provides info on the [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) generated by {@link formats!xkt.saveXKT | saveXKT}.
 *
 * See {@link "xkt" | @xeokit/xkt} for usage.
 */
export const XKT_INFO = {

  /**
   * The [XKT](https://xeokit.github.io/sdk/docs/pages/GLOSSARY.html#xkt) version generated by {@link formats!xkt.saveXKT | saveXKT}.
   *
   * @property xktVersion
   * @type {number}
   */
  xktVersion: 10
};
